### PR TITLE
Handle 'since' in addition to 'page' for pagination response

### PR DESCRIPTION
**Pull request by brianlangdon**
pagination may return either 'page' or 'since' in the header. 'since' was not being handled

Fixes: #2112.

### CODE REVIEW

**Comment by brianlangdon** [comment]
I've cleared the conflict introduced by PR #2154 would it be possible for somebody to approve and merge? @gmlewis , @wesleimp ?

**Comment by gmlewis** [comment]
> I've cleared the conflict introduced by PR #2154 would it be possible for somebody to approve and merge? @gmlewis , @wesleimp ?

Thank you, @brianlangdon - can you please run `go fmt` on your file and push the changes?

**Comment by brianlangdon** [comment]
@gmlewis, changes pushed I hope!, Thanks

**Comment by gmlewis** [comment]
Thank you, @brianlangdon !  LGTM.

> I've cleared the conflict introduced by PR #2154 would it be possible for somebody to approve and merge? @gmlewis , @wesleimp ?

Please note that _ALL_ other contributors to this repo are welcome to provide the second PR review/comment/approval that we need for merging.

Perhaps @Parker77 has time today to review.

**Review by Parker77 — APPROVED** [review]
LGTM.

**Comment by gmlewis** [comment]
> LGTM.

Thank you, @Parker77 !
Merging.

**Comment by lonre** [comment]
Hi, @gmlewis @brianlangdon 

It sees that this break `https://docs.github.com/en/rest/reference/repos#list-commits` with since params

**Comment by gmlewis** [comment]
> Hi, @gmlewis @brianlangdon
> 
> It sees that this break `https://docs.github.com/en/rest/reference/repos#list-commits` with since params

Hi @lonre - could you please be more specific?  

How did it break?

Can you please give an example of the response (before and after, or "working" and "broken")?

**Comment by lonre** [comment]
Hi @gmlewis 

with `https://api.github.com/repos/Homebrew/homebrew-cask/commits?since=2021-12-04T10%3A43%3A42Z` request,

the response `NextPage` and `LastPage` is `0`, the pagination is broken

**Comment by gmlewis** [comment]
Thank you for more details, @lonre !
I'll re-open #2112 and show my findings there.

**Pull request merged**
