### PR TITLE
Add auto_merge field in PullRequest struct

### PR DESCRIPTION
**Pull request by slayer321**
@gmlewis
I have added the changes required for issue #1881
I had run go test ./... before and after the changes. I could see all test cases passing in /github folder.

Thanks,

### CODE REVIEW

**Comment by gmlewis** [comment]
Friendly ping @wesleimp

**Review by Parker77 — APPROVED** [review]
LGTM.

**Comment by simongottschlag** [comment]
Woop woop! Thank you @slayer321 @gmlewis @Parker77 😁🥇🎉🚀

**Comment by gmlewis** [comment]
Fixes: #1881.

**Pull request merged**
