### PR TITLE
Make auto-generated files read-only

### PR DESCRIPTION
**Pull request by gmlewis**
This PR is to assist new contributors to the repo and hopefully reduce the number of times that people try to edit the auto-generated files.

It makes these files read-only by default and also directs them to run `go generate ./...` and more importantly, read the instructions in CONTRIBUTING.md.

### CODE REVIEW

**Comment by gmlewis** [comment]
Awaiting LGMT+Approval from any other contributor to this repo.

**Comment by gmlewis** [comment]
> Merging [#2323](https://codecov.io/gh/google/go-github/pull/2323?src=pr&el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=google) ([c28324a](https://github.com/google/go-github/commit/c28324a366466569b3dc26fc89faa187e5e60c75)) into [master](https://codecov.io/gh/google/go-github/commit/3e8a7f0fbe0e4402f9ad5a80e0ab0a050786e0f8?el=desc&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=google) ([3e8a7f0](https://github.com/google/go-github/commit/3e8a7f0fbe0e4402f9ad5a80e0ab0a050786e0f8)) will **decrease** coverage by `0.00%`.
> The diff coverage is `n/a`.

This report can be ignored.

**Review by raynigon — APPROVED** [review]
LGTM

**Comment by gmlewis** [comment]
Thank you, @raynigon !
Merging.

**Pull request merged**
