### PR TITLE
Allow Installation of Custom Properties Permissions

### PR DESCRIPTION
**Pull request by shellz-n-stuff**
## Description
This PR allows app installations to request tokens with access to the Org level Custom Properties APIs

## Refs
1. [GitHub App installation access tokens](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app)
2. [API Docs](https://docs.github.com/en/rest/orgs/custom-properties?apiVersion=2022-11-28#get-a-custom-property-for-an-organization)

### CODE REVIEW

**Comment by shellz-n-stuff** [comment]
CLA Signed 🙏

**Comment by gmlewis** [comment]
Thank you, @shellz-n-stuff !
Please run step 4 of CONTRIBUTING.md and push the changes to this PR.

**Comment by shellz-n-stuff** [comment]
My bad re-lint/generate. All updated 🙏

**Review by gmlewis — APPROVED** [review]
Thank you, @shellz-n-stuff !
LGTM.
Merging.

**Pull request merged**
