### PR TITLE
Add support for parsing code_scanning_alerts in webhooks

### PR DESCRIPTION
**Pull request by emilva**
Following up on the issue I created https://github.com/google/go-github/issues/2391. 

Let me know if there is anything missing or needs fixing. I just tried to follow the patterns from the other types.

Cheers,

emil

Fixes: #2391.

### CODE REVIEW

**Review by gmlewis — APPROVED** [review]
Thank you, @emilva !
LGTM.

Awaiting second LGTM from any other contributor to this repo before merging.

**Comment by emilva** [comment]
Thanks @gmlewis! :D

**Review by raynigon — APPROVED** [review]
LGTM

**Comment by gmlewis** [comment]
Thank you, @raynigon !
Merging.

**Pull request merged**
