### PR TITLE
Add previous_filename to CommitFile

### LINKED ISSUE #1046: github.CommitFile is missing previous_filename field
While seemingly undocumented, (over at https://developer.github.com/v3/repos/commits/#compare-two-commits ) this field is present for a status of `renamed`.

### PR DESCRIPTION
**Pull request by lukebjerring**
Fixes #1046

### CODE REVIEW

**Comment by gmlewis** [comment]
Thank you, @lukebjerring! I've contacted GitHub Developer API tech support and asked them to update their docs.

In the meantime, could you please take a look at our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) document and run `go generate ./...` and send another commit to this PR with the updated changes?  That should fix the Travis CI build. Thanks.

**Comment by lukebjerring** [comment]
Apologies, I had just quickly created the PR in GitHub's UI; will do that now.

**Comment by lukebjerring** [comment]
Ok, amended the output of `go generate ./...` and re-pushed, PTAL.

**Comment by gmlewis** [comment]
General comment... in the future, please do not force-push commits because that overwrites earlier commits and makes it more difficult for reviewers to see what changed since the last code review.

It's not a big deal in this PR, but just wanted to point that out, FYI.

**Pull request merged**
