### PR TITLE
Fixed ListPlanAccountsForAccount

### PR DESCRIPTION
**Pull request by domsu**
Fix for https://github.com/google/go-github/issues/1270

### CODE REVIEW

**Comment by gauntface** [comment]
I will defer to @gmlewis but from from glance this looks like it would be better off being a new method.

**Comment by gmlewis** [comment]
Thank you, @gauntface. Looking at the GitHub docs, this situation is very confusing indeed.

The docs show a single object being returned, yet imply that paging is supported with the call, and I don't know why.

Before we review and continue with this PR, @domsu - can you please contact support@github.com and ask them why paging is supported in this endpoint if it returns only a single object?

If they decide to remove paging support, then I think the method rename is appropriate along with the removal of the `ListOptions`. If, however, we learn something else from them, we can respond appropriately.

Thank you, @domsu!

**Comment by marco-m** [comment]
Hello @domsu, do you have time to follow-up @gmlewis request? What is the status of this PR? Thanks.

**Comment by gmlewis** [comment]
This PR appears to have been abandoned. Closing.

**Pull request closed without merging**
