### PR TITLE
Set up Dependabot for gomod and github-actions dependencies 

### PR DESCRIPTION
**Pull request by mmorel-35**

### CODE REVIEW

**Comment by gmlewis** [comment]
What is this for and why are you submitting this PR?

**Comment by mmorel-35** [comment]
Hi! I saw it defined in https://github.com/google/go-querystring, I thought the project might be interested

**Comment by gmlewis** [comment]
@willnorris - I defer to your judgment on this one and #2020.

**Comment by willnorris** [comment]
Hey @mmorel-35, thanks or these changes.  Just to help keep PRs a bit more focused on specific things, could we keep this one limited to the dependabot changes, and make those other testing changes in a separate PR with clearer messages on what they're doing and why?

**Comment by willnorris** [comment]
And honestly, I'd love to just check-in the dependabot config without the go.mod changes, since that will also let us test that dependabot bumps those dependencies itself.

**Comment by mmorel-35** [comment]
Alright, I'm closing this pr and will open dedicated prs

**Comment by willnorris** [comment]
oh, I didn't mean to close this one necessarily.  We still need the original commit to update the dependabot config.  I just meant reverting the other unrelated commits in this PR.  Then, we I do a squash merge, it'll reduce it back to just the dependabot change.

**Comment by mmorel-35** [comment]
Don't worry, it's in #2047, now

**Comment by mmorel-35** [comment]
And #2054, for the cache part

**Pull request closed without merging**
