### PR TITLE
Add date to the User struct, it's sometimes used for committer and author dates

### PR DESCRIPTION
**Pull request by brendandburns**
e.g. https://api.github.com/repos/googlecloudplatform/kubernetes/commits/7ad83079263ea73e022936887e67f267e41fd211

### CODE REVIEW

**Comment by brendandburns** [comment]
An alternate fix would be to change `RepositoryCommit.Comitter` to be a `CommitAuthor` rather than a `User`, let me know which one you prefer.

**Comment by brendandburns** [comment]
or, even have `PullRequest.ListCommits(...)` return a `[]Commit` instead of `[]RepositoryCommit`

**Comment by willnorris** [comment]
Are you sure you don't mean to be fetching the `RepositoryCommit.Commit.Committer`, which is a `CommitAuthor`?  As opposed to the `RepositoryCommit.Committer`, which is a `User`.

**Comment by brendandburns** [comment]
Ah, you are correct!  sorry for the noise!

**Pull request closed without merging**
