### PR TITLE
improve docs of (Set|Delete)RepositorySubscription 

### LINKED ISSUE #477: Improve docs of SetRepositorySubscription to make it more clear it can be used to watch/unwatch repos.
PR #428, which tried to add legacy GitHub API endpoints, came to be because the [documentation of `SetRepositorySubscription`](https://godoc.org/github.com/google/go-github/github#ActivityService.SetRepositorySubscription) in go-github is not very clear about the fact that those endpoints can be used to watch/unwatch repos. In fact, they're the preferred current (non-legacy) way of doing it.

The documentation on GitHub API docs says that in these blue boxes:

image
image

Source: https://developer.github.com/v3/activity/watching/#set-a-repository-subscription

image

Source: https://developer.github.com/v3/activity/watching/#delete-a-repository-subscription

I think we should copy that into go-github documentation so people are more likely to find what they need, without wanting to try to add support for missing legacy endpoints.

This is is a followup task from discussion in #428. See https://github.com/google/go-github/pull/428#issuecomment-246161269 and below.

### PR DESCRIPTION
**Pull request by JRonak**
fixes #477

### CODE REVIEW

**Comment by shurcooL** [comment]
Thanks for getting this fix started @JRonak. You've enabled edits from maintainers, so I'll just make my suggestions to improve this PR by editing the file. Let me know what you think of the end result after.

**Comment by shurcooL** [comment]
@JRonak Take another look. I've pushed 2 commits to your PR branch. See if it looks good to you and let me know. I've written my motivation for the edits in the commit messages.

**Comment by shurcooL** [comment]
@googlebot I'm okay with these commits being contributed to Google. :)

**Comment by gmlewis** [comment]
Thank you, @JRonak and @shurcooL!
LGTM.
Merging.

**Comment by gmlewis** [comment]
Included in https://github.com/google/go-github/commit/5c45bca952b96dedace6c307caff915483013003

**Comment by JRonak** [comment]
@shurcooL Yes I am good with it.
Thanks

**Pull request closed without merging**
