### PR TITLE
Fix ineffectual assignments and error handling in tests

### PR DESCRIPTION
**Pull request by muesli**
- Ignore ineffectual assignments
- Check for error when reading keyring

### CODE REVIEW

**Comment by gmlewis** [comment]
Thanks, @muesli - I'm the one that wrote these additional tests for the sake of code coverage improvements.  If you're going to do this, please go through and fix _all_ the added code coverage tests so that the repo is self-consistent in style.

**Comment by muesli** [comment]
@gmlewis I don't think it would affect code coverage, but I'm happy to remove the other ineffectual assignments I can find.

**Comment by muesli** [comment]
@gmlewis Ok, hope I caught them all.

**Comment by gmlewis** [comment]
OK, looks like these changes did not affect code coverage, and my original PRs were done to improve coverage (without review), so I'm just going to go ahead and merge this as a code cleanup.
Thanks, @muesli.

**Comment by muesli** [comment]
No problem, thanks for merging!

**Pull request merged**
