### PR TITLE
Change DependabotSecretsSelectedRepoIDs to []string

### PR DESCRIPTION
**Pull request by gmlewis**
Fixes: #2400.

### CODE REVIEW

**Comment by gmlewis** [comment]
@lneves75 - could you please review and approve if you agree to this change when you have a chance?

**Comment by gmlewis** [comment]
Awaiting LGTM+Approval from two contributors to this repo before merging.

**Comment by lneves75** [comment]
@gmlewis apparently the problem lies on github's API implementation for both endpoints.
If we call the endpoint `/orgs/myorg/actions/secrets/BAR` with a set of strings we get a 422
```json
{
	"message": "Invalid request.\n\nFor 'items', \"123\" is not an integer.\nFor 'items', \"456\" is not an integer.",
	"documentation_url": "https://docs.github.com/rest/reference/actions#create-or-update-an-organization-secret"
}
```

So I'm afraid that we need to have two distinct types 😞 
```go
type ActionSecretsSelectedRepoIDs []int64
type DependabotSecretsSelectedRepoIDs []string
```  
WDYT ?

**Comment by timrogers** [comment]
> OK, that is really weird. Can you please contact GitHub tech support and verify this correct?

👋🏻 Hey there! I'm the PM for the API at GitHub, and I happened to just spot this thread.

I can confirm that the current behaviour of the API is that:

* the Actions "[Create or update an organization secret](https://docs.github.com/en/rest/actions/secrets#create-or-update-an-organization-secret)" API only has documented support for an array of integers, but it actually accepts strings or integers. (Until recently, it said it was an array of strings.)
* the Dependabot "[Create or update an organization secret](https://docs.github.com/en/rest/dependabot/secrets#create-or-update-an-organization-secret)" API only supports an array of strings

This is obviously a bit weird at the moment and is something we need to clean up - but in a way that avoids breaking changes for users!

**Comment by gmlewis** [comment]
> 👋🏻 Hey there! I'm the PM for the API at GitHub, and I happened to just spot this thread.

Hi @timrogers - it's great to have you here!  Thank you to you and your team for an amazing product... it is greatly appreciated!

> I can confirm that the current behaviour of the API is that:
> 
> * the Actions "[Create or update an organization secret](https://docs.github.com/en/rest/actions/secrets#create-or-update-an-organization-secret)" API only has documented support for an array of integers (although in practice it actually accepts strings or integers). (Until recently, the docs said it should be an array of strings.)
> * the Dependabot "[Create or update an organization secret](https://docs.github.com/en/rest/dependabot/secrets#create-or-update-an-organization-secret)" API only supports an array of strings

If I'm reading this correctly, then making them both use an array of strings should work.
However, when we tried this here: https://github.com/google/go-github/pull/2401/commits/e3028fbc563b35173008debb2bcabd9eddf63c83
it failed... see comment from @lneves75 above: https://github.com/google/go-github/pull/2401#issuecomment-1168648355

So then we tried splitting it into two separate implementations, as you see this PR now.

> Sorry for the pain! This is obviously a bit weird at the moment and is something we need to clean up - but in a way that minimises breaking changes for users.

No problem... we would just like to get it working, so if you have recommendations on how to proceed, that would be great.
We don't mind updating the repo when/if it changes... we are updating this repo all the time.  :smile:

**Comment by timrogers** [comment]
@gmlewis So sorry - you’re right, I showed too much confidence and I actually misread the internal PR 😅: the Actions API really does only accept integers, whereas before it claimed incorrectly in the docs to accept strings.

Looking at the inputs, integers seem like the right data type, so I will raise an issue with the Dependabot team to look at making this more consistent in a non-breaking way.  

Very glad I came by this repo to discover this and see all of the great work you’re doing to make the API accessible to Go developers ❤️

**Comment by timrogers** [comment]
In other words, it looks like you’re doing exactly what you need to do in this PR!

**Comment by gmlewis** [comment]
> Very glad I came by this repo to discover this and see all of the great work you’re doing to make the API accessible to Go developers

Thank you so much, @timrogers !

We really appreciate your input, and we always love to hear from GitHub team members and tech support whenever we can.  :smile:

**Review by raynigon — APPROVED** [review]
LGTM

**Comment by gmlewis** [comment]
Thank you, @raynigon !
Merging.

**Pull request merged**
