### PR TITLE
Turn `RequiredStatusChecks` `Checks` and `Contexts` into pointers

### PR DESCRIPTION
**Pull request by emmahsax**
By making the both `Contexts` and `Checks` pointers, the JSON will allow sending an empty slice as `[]` to the GitHub API, instead of taking those out and sending `nil` or `null`.

This will actually solve both https://github.com/google/go-github/issues/2976 and https://github.com/google/go-github/issues/2467.

I also clarified in the comments that empty slices are allowed, implying that if the user wants to set no checks or contexts, to allow passing an empty slice.

These changes allow the Go API to properly reflect the behavior of the GitHub API.

### CODE REVIEW

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @emmahsax !
Please run the commands in step 4 found in CONTRIBUTING.md and then we should be ready for a second LGTM+Approval before merging.

**Review by gmlewis — APPROVED** [review]
Thank you, @emmahsax !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

**Review by valbeat — APPROVED** [review]
LGTM!

**Comment by gmlewis** [comment]
Thank you, @valbeat !
Merging.

**Comment by ttomsu** [comment]
Hi @gmlewis ! Could we get this released in a `v60` release soon? Thank you!

**Comment by gmlewis** [comment]
> Hi @gmlewis ! Could we get this released in a `v60` release soon? Thank you!

@ttomsu - this is now available in: https://github.com/google/go-github/releases/tag/v60.0.0

**Pull request merged**
