### PR TITLE
Fix package name escaping in UserService

### PR DESCRIPTION
**Pull request by DiegoDev2**
### Description

This pull request addresses the issue described in [#3262](https://github.com/google/go-github/issues/3262) by adding support for the PackageName escaping in the go-github library.
### Changes Made

 Updated the `UserService.GetPackage` method to escape package names consistently using `url.PathEscape`, aligning it with the `OrganizationsService.GetPackage`.

This change ensures consistent handling of package names across the API, improving overall reliability and usability.

### CODE REVIEW

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @DiegoDev2.
Please update the unit tests to demonstrate the new behavior.

**Comment by DiegoDev2** [comment]
okay

**Comment by DiegoDev2** [comment]
Hi @gmlewis ! Today I advanced the tests, maybe I won't be able to finish them today since I have some errors. I'll fix them tomorrow, is that okay with you?

**Comment by gmlewis** [comment]
> I'll fix them tomorrow, is that okay with you?

Of course. No rush, no pressure. We appreciate your contributions whenever you are able.

**Comment by DiegoDev2** [comment]
I just realized that in the users test url [here](https://github.com/google/go-github/blob/master/github/users_packages_test.go#L141) has the same URL as [here](https://github.com/google/go-github/blob/master/github/orgs_packages_test.go#L130) 

In addition to that, the two urls are from orgs, in users it should be `https://api.github.com/users/github/packages/container/hello%2Fhello_docker` and not like that `https://api.github.com/orgs/github/packages/container/hello%2Fhello_docker` If I am wrong please correct me.

**Comment by gmlewis** [comment]
> If I am wrong please correct me.

If I'm not mistaken, these are simply values (test data) and therefore it doesn't matter what they are. If you find them confusing or unexpected, feel free to update them.

I'm looking at this from my cell phone, so I might not be understanding correctly what you are attempting to point out. If this is the case, I will take a more careful look tomorrow from my desktop machine.

**Comment by DiegoDev2** [comment]
> > If I am wrong please correct me.
> 
> If I'm not mistaken, these are simply values (test data) and therefore it doesn't matter what they are. If you find them confusing or unexpected, feel free to update them.
> 
> I'm looking at this from my cell phone, so I might not be understanding correctly what you are attempting to point out. If this is the case, I will take a more careful look tomorrow from my desktop machine.

okay it seems perfect to me.

**Comment by DiegoDev2** [comment]
Hi, sorry I'm late, but I've been busy with school and personal projects and I'm almost done with the tests. @gmlewis

**Comment by osvaldoabel** [comment]
good job, @DiegoDev2

**Comment by DiegoDev2** [comment]
> good job, @DiegoDev2 
> 
> 

Hi, thank you very much although I haven't been able to finish it yet, I haven't had time to finish it unfortunately

**Comment by osvaldoabel** [comment]
> > good job, @DiegoDev2
> 
> Hi, thank you very much although I haven't been able to finish it yet, I haven't had time to finish it unfortunately

please, let me know if you need any help to finish the contribution :]

**Comment by DiegoDev2** [comment]
Hi, I am really very sorry for you. Also, after reviewing a little, I realized that the change that was being made is not necessary, should we close this? @gmlewis

**Comment by DiegoDev2** [comment]
the issue too? @gmlewis

**Comment by gmlewis** [comment]
> the issue too? @gmlewis

Sure.  I'll close it too.

**Comment by gmlewis** [comment]
> the issue too? @gmlewis

After re-reading the original issue, I'm now confused as to why you suggest that it should be closed.
Doesn't the original issue still exist?

If not, could you please comment on #3262 why you think it is not an issue, @DiegoDev2 ?

**Pull request closed without merging**
