### PR TITLE
Add cryptographer-preview header to include GPG signed response in Re…

### LINKED ISSUE #687: RepositoriesService.ListCommits could also benefit from Preview support for Git signing.
While investigating #685, I noticed that `RepositoriesService.ListCommits` is also missing this header. Setting it would populate the `Verification` fields:

```
$ curl -s "https://api.github.com/repos/shurcooL/home/commits?per_page=1" | grep verification
$ curl -s "https://api.github.com/repos/shurcooL/home/commits?per_page=1" -H "Accept: application/vnd.github.cryptographer-preview" | grep verification
      "verification": {
```

/cc @RaviTezu FYI.

### PR DESCRIPTION
**Pull request by RaviTezu**
…positoryService's ListCommits method.

Fixes #687

### CODE REVIEW

**Comment by RaviTezu** [comment]
Yes! The builds aren't started yet. 
Probably something wrong at their end.

**Comment by RaviTezu** [comment]
@shurcooL I am sorry, I don't get it. 
I think I am missing something, I don't see how https://godoc.org/github.com/google/go-github/github#Repository.License field is impacted with this change.

**Comment by shurcooL** [comment]
It's not the field, but rather its documentation. It currently says:

```Go
// Only provided when using RepositoriesService.Get while in preview
License *License `json:"license,omitempty"`
```

That's no longer true.

**Comment by RaviTezu** [comment]
@shurcooL ok. But, how is this change makes the License field's doc invalid?
I am sorry again, I am having hard time seeing the reason.

**Comment by shurcooL** [comment]
Sorry @RaviTezu, I was mistaken. For some reason, I thought this PR and PR #686 were returning `Repository` and that `License` would now be populated after setting this preview header.

Now I see these two methods return `RepositoryCommits` and this change affects [`Commit.Verification`](https://godoc.org/github.com/google/go-github/github#Commit.Verification) field. Its documentation is fine and doesn't need to be updated.

Sorry about that! I can see how what I said made no sense at all. License isn't even related to this. :)

**Comment by RaviTezu** [comment]
No problem :) 
@shurcooL Thanks.

**Pull request merged**
