### PR TITLE
Add the AuthorAssociation field to PullRequestReview

### PR DESCRIPTION
**Pull request by qaisjp**
#892 and #802, electric boogaloo.

### CODE REVIEW

**Comment by gmlewis** [comment]
Thank you, @qaisjp.

As in #892, could you please contact support@github.com and request that they update their examples where appropriate on this page: https://developer.github.com/v3/pulls/reviews/#list-reviews-on-a-pull-request
to include this field and report back their response?

**Comment by qaisjp** [comment]
sent.

I suspect there will be more places where this is missing, a future PR author can use this canned message:

```
Some of the responses on https://developer.github.com/v3/pulls/reviews/ are missing the `author_association` key, specifically https://developer.github.com/v3/pulls/reviews/#list-reviews-on-a-pull-request.

The API is returning that info, but it's not documented. Is that a documentation mistake or should `author_association` not actually be in the response?
```

**Comment by qaisjp** [comment]
> Hello -
> 
> Thanks for the report and sorry for the delay!
> 
> I believe this is a documentation issue - we'll go ahead and mention this to our documentation team and if I find out differently, we'll let you know.
> 
> Thanks again for reporting!

**Comment by gmlewis** [comment]
Thank you for reporting back their response, @qaisjp!
It is greatly appreciated!

**Pull request merged**
