### PR TITLE
Add a GetLabel() accessor for the PullRequestLabel

### PR DESCRIPTION
**Pull request by cflewis**
PR #867 added a Label field to the PullRequestEvent, but I forgot to add the corresponding accessor. This fixes this oversight.

### CODE REVIEW

**Comment by willnorris** [comment]
ah yes.  That's almost certainly why Travis was failing.  I missed that.

**Comment by shurcooL** [comment]
It looks like the accessor wasn't added in the right spot, and it's causing CI to continue to fail:

```diff
$ go generate -x ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)
go run gen-accessors.go
diff --git a/github/github-accessors.go b/github/github-accessors.go
index 4813e96..597478e 100644
--- a/github/github-accessors.go
+++ b/github/github-accessors.go
@@ -6236,6 +6236,14 @@ func (p *PullRequestEvent) GetInstallation() *Installation {
 	return p.Installation
 }
 
+// GetLabel returns the Label field.
+func (p *PullRequestEvent) GetLabel() *Label {
+	if p == nil {
+		return nil
+	}
+	return p.Label
+}
+
 // GetNumber returns the Number field if it's non-nil, zero value otherwise.
 func (p *PullRequestEvent) GetNumber() int {
 	if p == nil || p.Number == nil {
@@ -6268,14 +6276,6 @@ func (p *PullRequestEvent) GetSender() *User {
 	return p.Sender
 }
 
-// GetLabel returns the Label field.
-func (p *PullRequestEvent) GetLabel() *Label {
-	if p == nil {
-		return nil
-	}
-	return p.Label
-}
-
 // GetDiffURL returns the DiffURL field if it's non-nil, zero value otherwise.
 func (p *PullRequestLinks) GetDiffURL() string {
 	if p == nil || p.DiffURL == nil {
The command "go generate -x ./... && git diff --exit-code; code=$?; git checkout -- .; (exit $code)" exited with 1.
```

Did you create it manually rather than using `go generate`?

**Comment by willnorris** [comment]
*sigh* thanks @shurcooL.  Can't believe I missed that twice in a row :(  Chris and I were talking about this in the office, and I neglected to look at the CI status carefully.  He's fixing it now.

**Comment by shurcooL** [comment]
No worries. I just created PR #869. :)

**Comment by cflewis** [comment]
It's my bad. It does say DO NOT EDIT at the top.

But here we are.

D'oh.

**Pull request merged**
