### PR TITLE
issues: add Repository

### PR DESCRIPTION
**Pull request by pcarrier**

### CODE REVIEW

**Comment by pcarrier** [comment]
I signed it!

**Comment by willnorris** [comment]
thanks!

**Comment by shurcooL** [comment]
When is this field set? Can you provide some examples or references?

I've chcked https://developer.github.com/v3/issues/ and I don't see `"repository"` anywhere.

I do see `"repository_url"`, but that's a string. Did you mean to add that instead?

**Comment by willnorris** [comment]
That's actually a good question.  I had the same thought, but forgot to double check it before merging this in.  When is this actually set?  Maybe on a webhook event I suspect?

**Comment by willnorris** [comment]
No, even on issue events, the repository is sent alongside the issue, not inside of it: https://developer.github.com/v3/activity/events/types/#issuesevent

**Comment by pcarrier** [comment]
It is sent on `/issues` and `/orgs/$org/issues`.

**Comment by willnorris** [comment]
ah yes, I see it there now (docs at https://developer.github.com/v3/issues/#list-issues don't show repository field, but I just tested and verified it). Thanks for confirming.

**Comment by shurcooL** [comment]
Thanks for confirming.

**Pull request merged**
