### PR TITLE
move README badges inline

### PR DESCRIPTION
**Pull request by rajendraarora16**

### CODE REVIEW

**Comment by gmlewis** [comment]
I defer to @willnorris on Markdown changes in README.md.

**Comment by willnorris** [comment]
I'm not really a fan of the table.  What about just putting them inline with the project name on the first line (similar to [willnorris/imageproxy](https://github.com/willnorris/imageproxy#readme)).  

For the docs, we could create a simple badge for that as well...

[Discuss at go-github@googlegroups.com](https://groups.google.com/group/go-github)

``` markdown
[![Discuss at go-github@googlegroups.com](https://img.shields.io/badge/discuss-go--github%40googlegroups.com-blue.svg)](https://groups.google.com/group/go-github)
```

**Comment by shurcooL** [comment]
Yeah, I like the inline style better too. It's what I used in the [`githubql`](https://github.com/shurcooL/githubql/blob/master/README.md) repo (and all my other repos).

My only request here is let's please continue to have the godoc badge first in the list, I think it's the most important one for most people.

**Comment by willnorris** [comment]
> let's please continue to have the godoc badge first in the list

agreed

**Comment by willnorris** [comment]
@rajendraarora16: do you want to try moving these directly inline as noted above, or I can quickly handle it for you?

**Comment by rajendraarora16** [comment]
@willnorris Let me do it pls ;)

**Comment by rajendraarora16** [comment]
@willnorris Changes are done, can we go ahead?

**Comment by willnorris** [comment]
As @shurcooL noted above, let's move the godoc link to the front. otherwise, looks good

**Comment by rajendraarora16** [comment]
@willnorris Is it good ?

**Comment by willnorris** [comment]
Let's move it to the very front... before the build status even.

**Comment by rajendraarora16** [comment]
@willnorris Updated!

**Comment by willnorris** [comment]
looks great, thanks!

**Pull request merged**
