### PR TITLE
Added DiffURL & PatchURL to PullRequest struct

### LINKED ISSUE #174: DiffURL & PatchURL is not available in PullRequest struct
I need to access the diff and patch urls that is being returned in the json structure but these attributes are currently not available in the PullRequest struct.

I will submit a pull request shortly that solves this issue.

### PR DESCRIPTION
**Pull request by freddd**
Hi,
I have run golint, fmt & tests, please let me know if there is anything else I should do as well.

Closes #174

### CODE REVIEW

**Comment by parkr** [comment]
Test?

**Comment by freddd** [comment]
Sorry, I must have been a bit eager to create the PR. I have included a test in the last commit. I'm looking into why travis is failing as well.

**Comment by parkr** [comment]
Might have hit GitHub's DDoS protections. They've been under some pretty crazy attack the last few days.

**Comment by freddd** [comment]
Yeah, most likely. It's building fine now.

**Comment by willnorris** [comment]
rebased onto master and merged as 8e3584dcc5126021ff8820cfcc7adda2f57cacdc and 2ecbc4667b7797b6d064e3e2a634f1573d592df0.  Thanks!

**Pull request closed without merging**
