### PR TITLE
Add test cases for JSON resource marshaling

### PR DESCRIPTION
**Pull request by sagar23sj**
Resources Covered :
- Page
- TeamChange

Relates to : #55

### CODE REVIEW

**Review by gmlewis — APPROVED** [review]
Thank you, @sagar23sj !
LGTM.

Awaiting second LGTM before merging.

**Comment by gmlewis** [comment]
Friendly ping @wesleimp

**Review by Parker77 — APPROVED** [review]
LGTM.

**Comment by gmlewis** [comment]
@sagar23sj - either you can resolve the conflicts or I can - either way is fine with me, please just let me know.

**Pull request closed without merging**
