### PR TITLE
Update from original

### PR DESCRIPTION
**Pull request by rakeshkumargupt**

### CODE REVIEW

**Comment by shurcooL** [comment]
Did you mean to open this PR here, or was it an accident?

**Comment by rakeshkumargupt** [comment]
I have already signed it!
Yes.. I want pull request. I am new and want to contribute..

**Comment by shurcooL** [comment]
Can you describe what is change you’re trying to contribute?

**Comment by rakeshkumargupt** [comment]
Hi @shurcooL I have already fork this repository long ago. Now i want to update my repository from original google/go-github. So i created pull request.

**Comment by shurcooL** [comment]
I see. You should be able to update your fork directly, there’s no need send a PR to this repository.

**Pull request closed without merging**
