### PR TITLE
Update comparisons in test files from reflect to cmp

### PR DESCRIPTION
**Pull request by sagar23sj**
Replaced all reflect.DeepEqual comparisons in test files with cmp.Equal.

Fixes: #1851

### CODE REVIEW

**Comment by sagar23sj** [comment]
Can someone help me understand, why checks are failing?
I ran all 3 commands go generate, go test, and go vet but still these are somehow failing in checks.

**Comment by willnorris** [comment]
Looks like there is still a reference to the reflect package, but it's not imported any longer:

```
Error: github/orgs_members_test.go:835:6: undefined: reflect
```

**Comment by sagar23sj** [comment]
> Looks like there is still a reference to the reflect package, but it's not imported any longer:
> 
> ```
> Error: github/orgs_members_test.go:835:6: undefined: reflect
> ```
> 
> https://github.com/google/go-github/pull/1875/checks?check_run_id=2677192197#step:8:9

Thanks for replying, but I checked there is no "reflect" imported for that particular file in the branch I created PR with.

**Comment by willnorris** [comment]
It looks like you need to rebase onto the upstream master branch, as you're missing some commits that apparently are getting picked up by the CI jobs (notably d39b94da583ae6dbe8f3039a95f7334fd47b253f).  

I don't entirely understand why it's not simply running the CI jobs against your branch, which should pass, but would then have problems come merge time.  Maybe it's automatically trying to merge your changes with master, resulting in these errors?

**Comment by sagar23sj** [comment]
> It looks like you need to rebase onto the upstream master branch, as you're missing some commits that apparently are getting picked up by the CI jobs (notably [d39b94d](https://github.com/google/go-github/commit/d39b94da583ae6dbe8f3039a95f7334fd47b253f)).
> 
> I don't entirely understand why it's not simply running the CI jobs against your branch, which should pass, but would then have problems come merge time. Maybe it's automatically trying to merge your changes with master, resulting in these errors?

Thanks @willnorris , I didn't realize my branch was not up to date.
Pushed again after rebasing, I hope checks pass now.

**Comment by willnorris** [comment]
okay, so now the error about the reflect reference in `orgs_members_test.go` is correct :)  You'll need to switch that one to use the cmp package as well.

**Comment by sagar23sj** [comment]
> okay, so now the error about the reflect reference in `orgs_members_test.go` is correct :) You'll need to switch that one to use the cmp package as well.

Thanks for helping @willnorris . I have fixed the issue and seems like checks also passed.

**Review by gmlewis — APPROVED** [review]
Thank you, @sagar23sj and @willnorris !
LGTM.

Awaiting second LGTM before merging.

**Review by willnorris — APPROVED** [review]

**Comment by willnorris** [comment]
@gmlewis oops, looks like I missed catching your issue rename before merging :)

**Comment by gmlewis** [comment]
:joy: No problem, Will!

**Pull request merged**
