### PR TITLE
feat: add Installation field in WorkflowRunEvent

### PR DESCRIPTION
**Pull request by missedone**

### CODE REVIEW

**Comment by rr-nick-tan** [comment]
hi guys, this PR is just show you the `Installation` field is missing, pls add it, thx

**Comment by gmlewis** [comment]
@rr-nick-tan - I'm not finding an `installation` field in the WorkflowRunEvent documentation: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_run

Why do you think that this field is missing?

**Comment by gmlewis** [comment]
> @rr-nick-tan - I'm not finding an `installation` field in the WorkflowRunEvent documentation: https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#workflow_run
> 
> Why do you think that this field is missing?

Oh, I apologize... it should be common to all events.  Gotcha.  I'll add it.  Thank you!

**Comment by rr-nick-tan** [comment]
@gmlewis , yes, that's common field.

BTW, could you also add field `check_suite_id` in workflow_run, though I don't see it's mentioned in the official doc , but there similar discussion here https://githubmemory.com/repo/octokit/webhooks/issues/406

I do see the field in the webhook payload
iShot2021-09-19 13 32 28

thank you very much

**Comment by gmlewis** [comment]
> BTW, could you also add field `check_suite_id` in workflow_run, though I don't see it's mentioned in the official doc , but there was similar discussion here https://githubmemory.com/repo/octokit/webhooks/issues/406

Done.  Please see #2101.

**Comment by rr-nick-tan** [comment]
thx @gmlewis

**Pull request closed without merging**
