### PR TITLE
Add test case for JSON resource marshaling

### PR DESCRIPTION
**Pull request by rahulkarmore**
Hi creator,
Added test cases for JSON Resources :
ExternalGroup
Helps: https://github.com/google/go-github/issues/55

I have followed all the guidelines to contribute to this repository.
Please revert in case of any changes are needed.
I am a first-time contributor to Hackoctober, It will be a great help if u can encourage me & accept my contribution.

### CODE REVIEW

**Review by gmlewis — APPROVED** [review]
Thank you, @rahulkarmore !
LGTM.

Waiting for GitHub Actions to perform all checks before merging.

**Comment by gmlewis** [comment]
@rahulkarmore - if GitHub Actions doesn't kick in within an hour or so, please feel free to tweak one of your constants in your PR and push the change to this PR... hopefully that will kick GHA into gear... it looks like it is currently either having issues or is just sleeping.  :grin:

**Comment by gmlewis** [comment]
Thank you, @rahulkarmore !  Do you want to resolve the conflicts by merging in the master branch (again), or would you like me to do that?

**Comment by rahulkarmore** [comment]
resolved conflict

**Pull request merged**
