### PR TITLE
Add Account field to MarketplacePurchase struct

### LINKED ISSUE #2658: Add Account field to MarketplacePurchase struct
Hi, 

Thanks for all the work on this library!

According to [the docs](https://docs.github.com/en/developers/github-marketplace/using-the-github-marketplace-api-in-your-app/webhook-events-for-the-github-marketplace-api), the `MarketplacePurchase` struct should have an `Account` field, but that field is currently missing.

I've checked the data sent by GitHub in the webhook, and we could either use the existing `MarketplacePlanAccount` type for the missing `Account` field, or create a new type something like this:

```
// MarketplacePurchaseAccount represents a GitHub Account (user or organization) for a specific purchase.
type MarketplacePurchaseAccount struct {
    Type                     *string    `json:"type,omitempty"`
    ID                       *int64     `json:"id,omitempty"`
    Login                    *string    `json:"login,omitempty"`
    OrganizationBillingEmail *string    `json:"organization_billing_email,omitempty"`
}
```

The benefit of adding the new `MarketplacePurchaseAccount` type is that we would avoid making the definition of `MarketplacePurchase` recursive. (The existing `MarketplacePlanAccount` type has a `MarketplacePurchase` field).

Please let me know if you'd like me to open a PR.

### PR DESCRIPTION
**Pull request by lyspj**
Fixes #2658

### CODE REVIEW

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thanks, @lyspj .
The documentation example here: https://docs.github.com/en/rest/apps/marketplace?apiVersion=2022-11-28#list-subscriptions-for-the-authenticated-user-stubbed

Lists more fields:

```json
    "account": {
      "login": "github",
      "id": 4,
      "node_id": "MDEyOk9yZ2FuaXphdGlvbjE=",
      "url": "https://api.github.com/orgs/github",
      "email": null,
      "organization_billing_email": "billing@github.com",
      "type": "Organization"
    },
```

Could you please add them as well while we are here?

**Comment by lyspj** [comment]
> Thanks, @lyspj . The documentation example here: https://docs.github.com/en/rest/apps/marketplace?apiVersion=2022-11-28#list-subscriptions-for-the-authenticated-user-stubbed
> 
> Lists more fields:
> ...
> Could you please add them as well while we are here?

Sure! I've added `URL` `NodeID` `Email`, which I think covers all the remaining fields.

**Review by gmlewis — APPROVED** [review]
Thank you, @lyspj !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

**Review by valbeat — APPROVED** [review]
LGTM!

**Comment by gmlewis** [comment]
Thank you, @valbeat !
Merging.

**Pull request merged**
