### PR TITLE
Move to Protonmail PGP

### LINKED ISSUE #2317: golang.org/x/crypto/openpgp is deprecated
golang.org/x/crypto/openpgp is currently used to as an optional signing key: https://github.com/google/go-github/blob/master/github/git_commits.go#L27-L50

However this package is now deprecated: https://github.com/golang/go/issues/44226

### PR DESCRIPTION
**Pull request by komod0**
This changes the openpgp library so that it uses the Protonmail fork which seems to be the preferred one and it's the one [go-git has adopted](https://github.com/go-git/go-git/blob/7ab4957732a817bada223e5c361f0c9753d9e40c/go.mod#L4).
Closes #2317

### CODE REVIEW

**Comment by gmlewis** [comment]
I'm not sure why the tests are failing... all I could find is this: https://github.com/golangci/golangci-lint/issues/825
but that doesn't appear to match what is going on here.
Running `golangci-lint run` manually (locally) seems fine.  Very confusing.

**Comment by gmlewis** [comment]
When I check out your branch locally, I'm seeing this:

```
glenn@glenn-OMEN-875 ~/go/src/github.com/google/go-github (komod0-chore/movepgp) $ ./test-all.sh 
+ export GOROOT=/usr/local/go
+ GOROOT=/usr/local/go
+ diff -u /dev/fd/63 /dev/fd/62
++ echo -n
++ gofmt -d -s .
--- /dev/fd/63	2023-02-21 08:03:34.134780783 -0500
+++ /dev/fd/62	2023-02-21 08:03:34.134780783 -0500
@@ -0,0 +1,26 @@
+diff github/repos_commits_test.go.orig github/repos_commits_test.go
+--- github/repos_commits_test.go.orig
++++ github/repos_commits_test.go
+@@ -14,8 +14,8 @@
+ 	"testing"
+ 	"time"
+ 
+-	"github.com/google/go-cmp/cmp"
+ 	"github.com/ProtonMail/go-crypto/openpgp"
++	"github.com/google/go-cmp/cmp"
+ )
+ 
+ func TestRepositoriesService_ListCommits(t *testing.T) {
+diff github/repos_contents_test.go.orig github/repos_contents_test.go
+--- github/repos_contents_test.go.orig
++++ github/repos_contents_test.go
+@@ -14,8 +14,8 @@
+ 	"net/url"
+ 	"testing"
+ 
+-	"github.com/google/go-cmp/cmp"
+ 	"github.com/ProtonMail/go-crypto/openpgp"
++	"github.com/google/go-cmp/cmp"
+ )
+ 
+ func TestRepositoryContent_GetContent(t *testing.T) {
glenn@glenn-OMEN-875 ~/go/src/github.com/google/go-github (komod0-chore/movepgp) $ go version
go version go1.19.5 linux/amd64
```

What do you see?

**Comment by komod0** [comment]
Where can i find the `test_all.sh` script to try that?

**Comment by gmlewis** [comment]
> Where can i find the `test_all.sh` script to try that?

It's nothing special... just something I threw together to help me out with this repo:

```bash
$ cat test-all.sh 
#!/bin/bash -ex

# https://github.com/golangci/golangci-lint/issues/3107
export GOROOT=/usr/local/go

diff -u <(echo -n) <(gofmt -d -s .)
go mod tidy
go generate ./...
go test ./...
go vet ./...
golangci-lint run

cd scrape
go mod tidy
go generate ./...
go test ./...
go vet ./...
golangci-lint run

cd ../update-urls
go mod tidy
go generate ./...
go test ./...
go vet ./...
golangci-lint run
```

**Comment by komod0** [comment]
I think it's similar except the version
```
❯ ./test_all.sh
+ export GOROOT=/usr/local/go
+ GOROOT=/usr/local/go
+ diff -u /dev/fd/63 /dev/fd/62
++ echo -n
++ gofmt -d -s .
--- /dev/fd/63  2023-02-22 01:15:08
+++ /dev/fd/62  2023-02-22 01:15:10
@@ -0,0 +1,26 @@
+diff -u github/repos_commits_test.go.orig github/repos_commits_test.go
+--- github/repos_commits_test.go.orig  2023-02-22 01:15:10
++++ github/repos_commits_test.go       2023-02-22 01:15:10
+@@ -14,8 +14,8 @@
+       "testing"
+       "time"
+ 
+-      "github.com/google/go-cmp/cmp"
+       "github.com/ProtonMail/go-crypto/openpgp"
++      "github.com/google/go-cmp/cmp"
+ )
+ 
+ func TestRepositoriesService_ListCommits(t *testing.T) {
+diff -u github/repos_contents_test.go.orig github/repos_contents_test.go
+--- github/repos_contents_test.go.orig 2023-02-22 01:15:10
++++ github/repos_contents_test.go      2023-02-22 01:15:10
+@@ -14,8 +14,8 @@
+       "net/url"
+       "testing"
+ 
+-      "github.com/google/go-cmp/cmp"
+       "github.com/ProtonMail/go-crypto/openpgp"
++      "github.com/google/go-cmp/cmp"
+ )
+ 
+ func TestRepositoryContent_GetContent(t *testing.T) {
❯ go version
go version go1.17.12 darwin/amd64
```

**Comment by gmlewis** [comment]
OK, then please try running gofmt on those files that you modified to see if that fixes the payment then push the changes to this PR.

**Comment by komod0** [comment]
@gmlewis Done

**Review by gmlewis — APPROVED** [review]
Thank you, @komod0 !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

**Review by valbeat — APPROVED** [review]
LGTM!

**Comment by gmlewis** [comment]
Thank you, @valbeat !
@komod0 - would you like to resolve the  go.mod/go.sum conflicts yourself by typing:

```
git checkout master
git pull
git checkout chore/movepgp
git merge master
go mod tidy -compat=1.17
git push origin chore/movepgp
```

or would you like me to do it?

**Comment by komod0** [comment]
@gmlewis Hey!, i just saw your comment, i fixed the conflicts manually and run `go mod tidy` after that, i think it should be the same

**Pull request merged**
