### PR TITLE
Export ArchiveFormat

### PR DESCRIPTION
**Pull request by gmlewis**
Fixes: #1533.

### CODE REVIEW

**Comment by gmlewis** [comment]
Friendly ping, @wesleimp - I would like to get this breaking API change into the repo before releasing `v32.0.0` so that we don't have to immediately bump the version after release.

**Comment by gmlewis** [comment]
Thank you, @andrew-waters!  Your review is greatly appreciated!  Oh, and @z0mbix too!  Thank you!
You all rock!

**Comment by gmlewis** [comment]
Merging.

**Comment by gmlewis** [comment]
Ah, thank you, @wesleimp !!!  You rock too!  :smile:

**Comment by wesleimp** [comment]
> Friendly ping, @wesleimp - I would like to get this breaking API change into the repo before releasing `v32.0.0` so that we don't have to immediately bump the version after release.

@gmlewis I somehow missed the notification. Sorry for that

**Comment by gmlewis** [comment]
No problem, @wesleimp !  It was no big deal, but today we got a request for a new release, so this one suddenly became important.  Thanks for your fast response!

**Pull request merged**
