### PR TITLE
Add test cases for JSON resource marshaling

### PR DESCRIPTION
**Pull request by sagar23sj**
Resources Covered :

* FeedLink
* Feeds

Helps with issue: #55

### CODE REVIEW

**Review by gmlewis — APPROVED** [review]
Thank you, @sagar23sj !
LGTM.

Awaiting second LGTM before merging.

**Review by Parker77 — APPROVED** [review]
LGTM.

**Comment by sagar23sj** [comment]
Hi @gmlewis. this will also break I guess due to changes in #1900. I will fix this PR as soon as #1900 is merged.

**Comment by sagar23sj** [comment]
Hi @gmlewis, somehow i managed to ruin the PR while trying to rebase current branch with the latest merges on master.
Could you please help me fix this??

Steps i did : 
1. rebase local master with upstream/master
2. rebase working branch with local master
3. git pull origin branch_name
(since i was getting some error: Updates were rejected because the tip of your current branch is behind)
4. git push origin branch_name

**Comment by gmlewis** [comment]
Hmmm... this is now pretty challenging to fix and not worth the effort.

How about closing this PR and creating a new one with the two test additions for:

* FeedLink
* Feeds

?

**Comment by sagar23sj** [comment]
I can do that @gmlewis . Earlier I was thinking of force push the changes, but I read your comments on other PRs where you mentioned that it doesn't allow you to see the changes, so I didn't force push the changes.

I will close this PR then and raise a new one, but can you tell me how do i resolve merge conflicts for other PRs??

**Comment by gmlewis** [comment]
I'm away from my computer this weekend, but you can try a force push if you wish, or close and create new PRs if you wish... whichever is easier.

As for the other ones, creating new PRs might be just as easy as trying to merge. Your call.

**Comment by sagar23sj** [comment]
Ok @gmlewis . For the ruined PRs i will raise new ones and for other PRs I'll see what I can do.

Thanks and have a great weekend

**Pull request closed without merging**
