### PR TITLE
Revert "Fix: Remove Sort & Direction Fields From IssueListCommentsOptions"

### PR DESCRIPTION
**Pull request by gmlewis**
Reverts google/go-github#1584

### CODE REVIEW

**Comment by gmlewis** [comment]
@tamalsaha or @nightlark - if you could please review and approve this PR, that would be helpful.

**Comment by tamalsaha** [comment]
Thanks, LGTM!

**Comment by gmlewis** [comment]
Thank you, @tamalsaha !

Do you need me to cut a new `v36` release?

**Comment by tamalsaha** [comment]
Yes. v35.1.0 sounds good to me.

**Comment by gmlewis** [comment]
Excellent, thank you.
I went ahead and created `v35.1.0`: https://github.com/google/go-github/releases/tag/v35.1.0

**Pull request merged**
