### PR TITLE
add watch and unwatch

### PR DESCRIPTION
**Pull request by qianlnk**
https://developer.github.com/v3/activity/watching/#watch-a-repository-legacy

Watch a repository (LEGACY)
Stop watching a repository (LEGACY)

### CODE REVIEW

**Comment by qianlnk** [comment]
I signed it!

**Comment by qianlnk** [comment]
the git commit email is the other one of mine, What should I do？

**Comment by shurcooL** [comment]
Are there newer replacements available for those legacy endpoints?

**Comment by qianlnk** [comment]
does func  SetRepositorySubscription can replace it? But I think it is not intuitive.

**Comment by shurcooL** [comment]
I think so, yes.

From https://developer.github.com/v3/activity/watching/#set-a-repository-subscription:

> If you would like to watch a repository, set `subscribed` to `true`. If you would like to ignore notifications made within a repository, set `ignored` to `true`. If you would like to stop watching a repository, delete the repository's subscription completely.

That seems very reasonable to me. What about it do you find unintuitive?

Or are you referring to the [documentation of `SetRepositorySubscription`](https://godoc.org/github.com/google/go-github/github#ActivityService.SetRepositorySubscription) in go-github? If so, perhaps we should improve its documentation to be as clear as the GitHub API docs are.

I think we should avoid adding legacy/deprecated endpoints to go-github, if they're not neccessary (because a better replacement exists) and if they didn't already exist.

**Comment by qianlnk** [comment]
yeah, you are right. Before, I don't know how to set the subscription.  So I wrote watch and unwatch according to API.

thanks!

**Comment by shurcooL** [comment]
I think it'd be useful to include the text inside blue boxes in go-github documentation. Would you like to make a PR that adds these short paragraphs?

image
image

image

**Comment by shurcooL** [comment]
I'll close this PR because we've come to conclusion that these legacy GitHub API endpoints are not needed, but instead we should improve go-github [documentation of `SetRepositorySubscription`](https://godoc.org/github.com/google/go-github/github#ActivityService.SetRepositorySubscription) to mention they can be used to watch/unwatch repos.

I've opened issue #477 to track that. Closing this. Thanks @qianlnk.

**Pull request closed without merging**
