### PR TITLE
Add missing `LdapDn` field in Users class

### PR DESCRIPTION
**Pull request by anjanashenoy**

### CODE REVIEW

**Comment by anjanashenoy** [comment]
I signed it!

**Comment by gmlewis** [comment]
Did you run your code through `gofmt`?

**Comment by anjanashenoy** [comment]
> Did you run your code through `gofmt`?

No, how do I do that?

**Comment by gmlewis** [comment]
https://golang.org/cmd/gofmt/
`gofmt -w filename.go`

**Comment by gmlewis** [comment]
You don't need to edit the two auto-generated files... please see the `go generate ./...` section of CONTRIBUTING.md.

**Comment by anjanashenoy** [comment]
> You don't need to edit the two auto-generated files... please see the `go generate ./...` section of CONTRIBUTING.md.

oh okay, my bad. i think i fixed the issue

**Comment by gmlewis** [comment]
LGTM. Merging.

**Pull request merged**
