### PR TITLE
Add create repository with an initial commit with empty README

### PR DESCRIPTION
**Pull request by yuseferi**

### CODE REVIEW

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @yuseferi .
Instead of adding a new example that is almost identical to the `newrepo` example but with a new flag, please just edit the other example to add your new flag.

**Comment by yuseferi** [comment]
> Thank you, @yuseferi . Instead of adding a new example that is almost identical to the `newrepo` example but with a new flag, please just edit the other example to add your new flag.

sure. just updated.

**Review by gmlewis — CHANGES_REQUESTED** [review]
I think you just need to run `gofmt` on the modified file, and we should be ready to merge.

**Comment by yuseferi** [comment]
> I think you just need to run `gofmt` on the modified file, and we should be ready to merge.

Done

**Review by gmlewis — APPROVED** [review]
Thank you, @yuseferi !
LGTM.
Merging.

**Pull request merged**
