### PR TITLE
Add ListOptions to GetAdvancedSecurityActiveCommittersOrg

### PR DESCRIPTION
**Pull request by ganeshkumarsv**
Adding Pagination support for fetching active committers in an organization.

### CODE REVIEW

**Comment by gmlewis** [comment]
It looks like you are making a change that affects only Enterprise GitHub, correct?
According to the current documentation URL: https://docs.github.com/en/rest/billing?apiVersion=2022-11-28#get-github-advanced-security-active-committers-for-an-organization
there is no pagination supported by the current endpoint.

Is it different for GitHub Enterprise?

If so, please provide two docs URLs as seen in other methods in this repo.

**Comment by ganeshkumarsv** [comment]
I think the API endpoint is supported only for enterprise cloud: https://docs.github.com/en/enterprise-cloud@latest/rest/billing?apiVersion=2022-11-28#get-github-advanced-security-active-committers-for-an-organization

**Comment by gmlewis** [comment]
Oh, I see... the original URL was wrong then.  Thanks.

**Review by gmlewis — APPROVED** [review]
Thank you, @ganeshkumarsv !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

**Review by AbbanMustafa — APPROVED** [review]

**Comment by ganeshkumarsv** [comment]
@gmlewis can we merge the PR? we got 2 approvals now.

**Pull request merged**
