### PR TITLE
Add support for adding apps to branch protection

### PR DESCRIPTION
**Pull request by gposton**
This PR adds support for adding apps to branch protection rules.

### CODE REVIEW

**Comment by gposton** [comment]
@googlebot I signed it!

**Comment by gmlewis** [comment]
Is this related to #1275 and #1283 ?
If so, then I think this issue is already assigned and someone is working on it, and we need to close this.

In general, in this repo we try to make it clear who is working on what issues so that work is not duplicated.  As a result, PRs should in general be associated with open issues.

Thanks for your understanding, @gposton.

**Comment by gposton** [comment]
Yes, this addresses those issues as well.

**Comment by gmlewis** [comment]
Closing this issue as it was resolved in #1283.

**Pull request closed without merging**
