### PR TITLE
Add test cases for JSON resource marshaling

### PR DESCRIPTION
**Pull request by sagar23sj**
All resources are covered from event_types.go file.

Helps with issue: #55

### CODE REVIEW

**Comment by sagar23sj** [comment]
Hi @gmlewis, Please see if this is acceptable. If yes, then I will close the other PRs consisting of test cases for the event_types.go file.

**Review by gmlewis — APPROVED** [review]
Yes, @sagar23sj - this looks great... let's run with this.
Thank you!
LGTM.

Awaiting second LGTM before merging.

**Comment by sagar23sj** [comment]
Thanks, @gmlewis. I will go ahead and close other PRs then.

**Review by Parker77 — APPROVED** [review]
LGTM.

**Pull request merged**
