### PR TITLE
Add RunAttempt field for WorkflowJob

### PR DESCRIPTION
**Pull request by paveldvoinos**
Add RunAttempt field for WorkflowJob

### CODE REVIEW

**Comment by gmlewis** [comment]
Whups, it looks like the modified files need `gofmt` and/or you need to run `go generate ./...` in the top of the repo... both described in more detail in CONTRIBUTING.md. I'll wait until you do that and push the results.  Thanks.

**Comment by paveldvoinos** [comment]
@gmlewis I tried and `fmt` does no difference.

Also ,I have concerns that the linting check itself is broken: this is the error the step fails with:
```
Running [/home/runner/golangci-lint-1.44.0-linux-amd64/golangci-lint run --out-format=github-actions --verbose] in [] ...
  panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt
```

**Comment by gmlewis** [comment]
> @gmlewis I tried and `fmt` does no difference.
> 
> Also ,I have concerns that the linting check itself is broken: this is the error the step fails with:
> 
> ```
> Running [/home/runner/golangci-lint-1.44.0-linux-amd64/golangci-lint run --out-format=github-actions --verbose] in [] ...
>   panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt
> ```

Yes, it looks like we need to use `v3` here: https://stackoverflow.com/questions/71758856/github-action-for-golangci-lint-fails-with-cant-load-fmt

I'll investigate.

**Comment by gmlewis** [comment]
Hmmm... we are already using the latest version: https://github.com/golangci/golangci-lint-action/releases/tag/v3.3.1

You ran `go generate ./...` correct, @paveldvoinos ?

**Comment by paveldvoinos** [comment]
yes, generated files included

**Comment by gmlewis** [comment]
It looks like `golangci-lint` is really having problems right now:
https://github.com/google/go-github/pull/2576

**Comment by gmlewis** [comment]
@paveldvoinos - could you please `git pull` on the master branch and then merge it into this branch and push again to this PR?
Let's see if bumping the version of `golangci-lint` fixes the problem.
Thank you, and I apologize for the hassle.

**Comment by gmlewis** [comment]
That worked!  Merging.  Thank you for your patience, @paveldvoinos !

**Pull request merged**
