### PR TITLE
Fix typo in README URL

### PR DESCRIPTION
**Pull request by gmlewis**
Relates to: #2513.

Thank you, @steven-terrana for the original PR.

### CODE REVIEW

**Comment by gmlewis** [comment]
Awaiting LGTM+Approval from any contributor to this repo before merging.

**Comment by gmlewis** [comment]
@Parker77 - could you please review this when you have a chance and LGTM+Approve?

**Review by Parker77 — APPROVED** [review]
LGTM!

**Comment by gmlewis** [comment]
Thank you, @Parker77 !
Merging.

**Pull request merged**
