### PR TITLE
Update event_types.go

### PR DESCRIPTION
**Pull request by simpleelegant**
In my real project, I found this error.

### CODE REVIEW

**Comment by shurcooL** [comment]
Thanks @simpleelegant. The Go code you've submitted is not `gofmt`ed, but that can be fixed easily.

I can see evidence of this being true at https://developer.github.com/v3/activity/events/types/#pushevent. If you look at the [Webhook payload example](https://developer.github.com/v3/activity/events/types/#webhook-payload-example-15), its `commits` array and `head_commit` field consists of objects that have `id` and `tree_id` fields, but not `sha`.

However, it's a little unclear what the type `PushEvent` is supposed to represent. From GitHub documentation:

> The Events API `PushEvent` payload is described in the table below. The example payload below that is from a webhook delivery and will differ from the Events API `PushEvent` payload.

So, in order to resolve this potential issue, we need to figure out/confirm if the [`github.PushEvent`](https://godoc.org/github.com/google/go-github/github#PushEvent) type is meant to represent a payload from the Events API, or from a webhook delivery. Does anyone know this? The Go documentation for that type is not very specific:

```
PushEvent represents a git push to a GitHub repository.

GitHub API docs: http://developer.github.com/v3/activity/events/types/#pushevent
```

(As an aside, that link should be updated to https rather than http.)

**Comment by gmlewis** [comment]
Yes, the github.PushEvent type is used for both the Events API and for Webhook events since there is a great deal of overlap.

@simpleelegant - can you please provide an example `curl` request that shows what kind of problem you are seeing?

**Comment by simpleelegant** [comment]
Sorry everybody for my reply slowly.

@gmlewis No `curl` example. The scenario is I set a webhook on a repository on github.com for `push` event. And I written a server use `go-github` to receive the event from github.com. This problem is happened when I run `git push` to github.com, and `go-github` show error (sorry, I forgot the detail).

Bellow is a push event from a enterprise github:

```json
{
  "ref": "refs/heads/master",
  "before": "93c3548b64e356eb5e3b5ba90c4c8be1f6871a54",
  "after": "806a33760b557e0780dba8014b6901471a762ed6",
  "created": false,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "http://github3.example.com/simpleelegant/test/compare/93c3548b64e3...806a33760b55",
  "commits": [
    {
      "id": "806a33760b557e0780dba8014b6901471a762ed6",
      "distinct": true,
      "message": "Update Dockerfile",
      "timestamp": "2016-06-14T14:41:47+08:00",
      "url": "http://github3.example.com/simpleelegant/test/commit/806a33760b557e0780dba8014b6901471a762ed6",
      "author": {
        "name": "Wang Yujian",
        "email": "wangyujian@example.com",
        "username": "simpleelegant"
      },
      "committer": {
        "name": "Wang Yujian",
        "email": "wangyujian@example.com",
        "username": "simpleelegant"
      },
      "added": [

      ],
      "removed": [

      ],
      "modified": [
        "Dockerfile"
      ]
    }
  ],
  "head_commit": {
    "id": "806a33760b557e0780dba8014b6901471a762ed6",
    "distinct": true,
    "message": "Update Dockerfile",
    "timestamp": "2016-06-14T14:41:47+08:00",
    "url": "http://github3.example.com/simpleelegant/test/commit/806a33760b557e0780dba8014b6901471a762ed6",
    "author": {
      "name": "Wang Yujian",
      "email": "wangyujian@example.com",
      "username": "simpleelegant"
    },
    "committer": {
      "name": "Wang Yujian",
      "email": "wangyujian@example.com",
      "username": "simpleelegant"
    },
    "added": [

    ],
    "removed": [

    ],
    "modified": [
      "Dockerfile"
    ]
  },
  "repository": {
    "id": 18573,
    "name": "test",
    "full_name": "simpleelegant/test",
    "owner": {
      "name": "simpleelegant",
      "email": "wangyujian@example.com"
    },
    "private": false,
    "html_url": "http://github3.example.com/simpleelegant/test",
    "description": "",
    "fork": false,
    "url": "http://github3.example.com/simpleelegant/test",
    "forks_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/forks",
    "keys_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/keys{/key_id}",
    "collaborators_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/collaborators{/collaborator}",
    "teams_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/teams",
    "hooks_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/hooks",
    "issue_events_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/issues/events{/number}",
    "events_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/events",
    "assignees_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/assignees{/user}",
    "branches_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/branches{/branch}",
    "tags_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/tags",
    "blobs_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/git/blobs{/sha}",
    "git_tags_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/git/tags{/sha}",
    "git_refs_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/git/refs{/sha}",
    "trees_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/git/trees{/sha}",
    "statuses_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/statuses/{sha}",
    "languages_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/languages",
    "stargazers_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/stargazers",
    "contributors_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/contributors",
    "subscribers_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/subscribers",
    "subscription_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/subscription",
    "commits_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/commits{/sha}",
    "git_commits_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/git/commits{/sha}",
    "comments_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/comments{/number}",
    "issue_comment_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/issues/comments{/number}",
    "contents_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/contents/{+path}",
    "compare_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/compare/{base}...{head}",
    "merges_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/merges",
    "archive_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/{archive_format}{/ref}",
    "downloads_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/downloads",
    "issues_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/issues{/number}",
    "pulls_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/pulls{/number}",
    "milestones_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/milestones{/number}",
    "notifications_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/notifications{?since,all,participating}",
    "labels_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/labels{/name}",
    "releases_url": "http://github3.example.com/api/v3/repos/simpleelegant/test/releases{/id}",
    "created_at": 1463043873,
    "updated_at": "2016-05-12T09:04:33Z",
    "pushed_at": 1465886507,
    "git_url": "git://github3.example.com/simpleelegant/test.git",
    "ssh_url": "git@github3.example.com:simpleelegant/test.git",
    "clone_url": "http://github3.example.com/simpleelegant/test.git",
    "svn_url": "http://github3.example.com/simpleelegant/test",
    "homepage": null,
    "size": 105,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "forks_count": 2,
    "mirror_url": null,
    "open_issues_count": 0,
    "forks": 2,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "master",
    "stargazers": 0,
    "master_branch": "master"
  },
  "pusher": {
    "name": "simpleelegant",
    "email": "wangyujian@example.com"
  },
  "sender": {
    "login": "simpleelegant",
    "id": 6438,
    "avatar_url": "http://github3.example.com/avatars/u/6438?",
    "gravatar_id": "",
    "url": "http://github3.example.com/api/v3/users/simpleelegant",
    "html_url": "http://github3.example.com/simpleelegant",
    "followers_url": "http://github3.example.com/api/v3/users/simpleelegant/followers",
    "following_url": "http://github3.example.com/api/v3/users/simpleelegant/following{/other_user}",
    "gists_url": "http://github3.example.com/api/v3/users/simpleelegant/gists{/gist_id}",
    "starred_url": "http://github3.example.com/api/v3/users/simpleelegant/starred{/owner}{/repo}",
    "subscriptions_url": "http://github3.example.com/api/v3/users/simpleelegant/subscriptions",
    "organizations_url": "http://github3.example.com/api/v3/users/simpleelegant/orgs",
    "repos_url": "http://github3.example.com/api/v3/users/simpleelegant/repos",
    "events_url": "http://github3.example.com/api/v3/users/simpleelegant/events{/privacy}",
    "received_events_url": "http://github3.example.com/api/v3/users/simpleelegant/received_events",
    "type": "User",
    "site_admin": false,
    "ldap_dn": "CN=wangyujian WX367080,OU=PartnerUsers,DC=china,DC=example,DC=com"
  }
}
```

**Comment by shurcooL** [comment]
@gmlewis, note how [GitHub API docs](https://developer.github.com/v3/activity/events/types/#pushevent) say:

> The Events API `PushEvent` payload is described in the table below. The example payload below that is from a webhook delivery and will differ from the Events API `PushEvent` payload.

Since `PushEventCommit` is shared between Events API and Webhooks, but has different fields, I think we'll want to do something like this to resolve this issue:

```Go
// PushEventCommit represents a git commit in a GitHub PushEvent.
type PushEventCommit struct {
	... // common fields

	// The following fields are only populated by Events API.
	SHA *string `json:"sha,omitempty"`

	// The following fields are only populated by Webhook events.
	ID     *string `json:"id,omitempty"`
	TreeID *string `json:"tree_id,omitempty"`
}
```

It looks like the current `PushEventCommit` mixes up some fields from both contexts and does not document the boundary. It's missing `ID` and `TreeID`, which is what this PR is trying to fix.

**Comment by gmlewis** [comment]
Thanks, @shurcooL and @simpleelegant. I've created #379 to fix the issue which will close this PR when it is merged.

**Pull request closed without merging**
