### PR TITLE
Add ListOptions to ListSelectedReposForOrgSecret

### PR DESCRIPTION
**Pull request by gmlewis**
Fixes: #1882.

### CODE REVIEW

**Review by wesleimp — APPROVED** [review]
LGTM 💙

**Comment by gmlewis** [comment]
Thank you, @wesleimp !
Merging.

**Comment by patrickmarabeas** [comment]
@gmlewis can we get a fresh release please?

**Comment by gmlewis** [comment]
> @gmlewis can we get a fresh release please?

Sure, @patrickmarabeas - feel free to LGTM/Approve https://github.com/google/go-github/pull/1921 to move the process along.

**Comment by gmlewis** [comment]
https://github.com/google/go-github/releases/tag/v36.0.0 has been released.

**Pull request merged**
