### PR TITLE
Add test cases for JSON resource marshaling

### PR DESCRIPTION
**Pull request by vaibhavgholap23**
Hi creators,
I have added test case for :
HovercardOptions struct
under Helps:#55 issue

I have followed all the guidelines to contribute in this repository.
Please revert in case of any changes needed.
I am first time contributor of Hackoctober , It will be great if you review & accept my contribution.

### CODE REVIEW

**Comment by vaibhavgholap23** [comment]
> Hi creators, I have added test case for : HovercardOptions struct under Helps:#55 issue
> 
> I have followed all the guidelines to contribute in this repository. Please revert in case of any changes needed. I am first time contributor of Hackoctober , It will be great if you review & accept my contribution.

**Comment by vaibhavgholap23** [comment]
@andygrunwald pls accept my PR for Hackoctober fest contribution.

**Comment by andygrunwald** [comment]
@vaibhavgholap23 Not sure how I can help here.
I am not part of the maintainer team.

**Review by gmlewis — APPROVED** [review]
LGTM

**Pull request merged**
