### PR TITLE
Add find installation by org, repo and user API

### LINKED ISSUE #932: Support new endpoints to find app installations
https://developer.github.com/changes/2018-06-15-find-app-installations/

I'll work on supporting this feature if anyone else hasn't already worked on it.

### PR DESCRIPTION
**Pull request by haya14busa**
Fixes #932

Tested API with following script: https://gist.github.com/haya14busa/612373686d75c711baad1fbbcf17d5ed

### CODE REVIEW

**Comment by haya14busa** [comment]
Friendly ping

**Comment by jamiehannaford** [comment]
@gmlewis Would be awesome to get this in!

**Comment by gmlewis** [comment]
Agreed, @jamiehannaford! How about giving it an official code review and a corresponding LGTM with approval for me?

**Comment by gmlewis** [comment]
Thank you, @haya14busa and @jamiehannaford!
Merging.

**Comment by haya14busa** [comment]
Thanks :+1: ✨

**Pull request merged**
