### PR TITLE
Align Installation Permissions to latest GitHub v3 API reference

### PR DESCRIPTION
**Pull request by xun-guo-anzx**
This PR is to fix issue #1879 by updating InstallationPermissions struct with new properties included in API Document.

Changes include:
* Update document URL in comment
* Add support for environments, organization_secrets, organization_self_hosted_runners, secrets, secret_scanning_alerts, security_events and workflows
* Align test code with new fields

### CODE REVIEW

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @xun-guo-anzx !
Please run `go generate ./...` and then push (please do not force push) the commit to this PR to make the tests pass (as described in our `CONTRIBUTING.md` document).

**Comment by xun-guo-anzx** [comment]
Thanks @gmlewis for looking into this. I've run `go generate ./...` command as well as `go test` and `go vet` as described in `CONTRIBUTING.md`. Sorry for missing out one step before submitting the PR.

**Review by gmlewis — APPROVED** [review]
Thank you @xun-guo-anzx !
LGTM.

Awaiting second LGTM before merging.

**Review by wesleimp — APPROVED** [review]
LGTM 💙

**Comment by gmlewis** [comment]
Thank you, @wesleimp !
Merging.

**Comment by patrickmarabeas** [comment]
@gmlewis Would it be possible to create a new release? Thanks!

**Comment by gmlewis** [comment]
> @gmlewis Would it be possible to create a new release? Thanks!

Certainly!  Here you go: https://github.com/google/go-github/releases/tag/v35.3.0

**Pull request merged**
