### PR TITLE
Support for creating reaction for a release

### LINKED ISSUE #2194: Support for creating reaction for a release
Hi everybody!
I found that [this](https://docs.github.com/en/rest/reference/reactions#create-reaction-for-a-release) endpoint is missing its implementation over here. Do the maintainers intend to cover it? If yes, can I work on it?

### PR DESCRIPTION
**Pull request by viveknathani**
closes #2194

### CODE REVIEW

**Review by gmlewis — APPROVED** [review]
Thank you, @viveknathani !
LGTM.

Awaiting second LGTM (from any other go-github contributor) before merging.

**Comment by viveknathani** [comment]
@gmlewis It seems like the requested reviewer has not been active in this repository for quite some time (as per the pending PRs). Can we get somebody else to do the review if that is okay?

**Comment by gmlewis** [comment]
> @gmlewis It seems like the requested reviewer has not been active in this repository for quite some time (as per the pending PRs). Can we get somebody else to do the review if that is okay?

Hi @viveknathani .

Any contributor to this repo is welcome to review and approve PRs, but there are only a small number of people on the official "Reviewers" list that can be requested and I unfortunately can not modify that list like I could in the past.

**Comment by viveknathani** [comment]
All right @gmlewis. @sushmitaw could you do the code review over here since you have been a recent contributor to this repository?

**Comment by viveknathani** [comment]
@gmlewis Is there any other way we can move forward from here? Getting a second voluntary reviewer is not working out...

**Review by AGMETEOR — APPROVED** [review]

**Comment by AGMETEOR** [comment]
> All right @gmlewis. @ganeshkumarsv, @devfd, @sushmitaw, @AGMETEOR could you do the code review over here since you have been a recent contributor to this repository?

Sorry for any delays. I approve the changes.

**Comment by gmlewis** [comment]
Thank you, @AGMETEOR !
Merging.

**Pull request merged**
