### PR TITLE
Add TextMatch custom header to other search type custom headers

### PR DESCRIPTION
**Pull request by DarkMatterV**
Fix TextMatch Option doesn't work when search type is commits topics repositories or issues (#2385)

Fixes: #2385.

### CODE REVIEW

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @DarkMatterV !
Please make sure to run the modified files through `gofmt`.
See CONTRIBUTING.md for more details.

**Review by gmlewis — APPROVED** [review]
Thank you, @DarkMatterV !
LGTM.

Awaiting second LGTM from any other contributor to this repo before merging.

**Review by raynigon — APPROVED** [review]
LGTM

**Comment by gmlewis** [comment]
Thank you, @raynigon !
Merging.

**Pull request merged**
