### PR TITLE
Allow RemoveReviewers to remove only teams

### PR DESCRIPTION
**Pull request by nagl-resourcely**
# What?
Fixes a [JSON marshaling problem](https://github.com/google/go-github/issues/3336#issuecomment-2438435830) that causes spurious 422s when calling RemoveReviewrs with `TeamReviewers` but no `Reviewers`.

# Background
The github API requires `"reviewers"`. It permits `"reviewers": []` but not `"reviewers": null`. Try it:

```
echo "Show the problem"
curl -L \                                                            
  -X DELETE \   
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${PAT}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/${OWNER}/${REPO}/pulls/${NUMBER}/requested_reviewers \
  -d '{"team_reviewers":["the_senate"]}' 
{
  "message": "Invalid request.\n\n\"reviewers\" wasn't supplied.",
  "documentation_url": "https://docs.github.com/rest/pulls/review-requests#remove-requested-reviewers-from-a-pull-request",
  "status": "422"
}

echo "What if we just removed omitempty?"
curl -L \
  -X DELETE \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${PAT}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/${OWNER}/${REPO}/pulls/${NUMBER}/requested_reviewers \
  -d '{"reviewers": null, "team_reviewers":["the_senate"]}'
{
  "message": "Invalid request.\n\nFor 'properties/reviewers', nil is not an array.",
  "documentation_url": "https://docs.github.com/rest/pulls/review-requests#remove-requested-reviewers-from-a-pull-request",
  "status": "422"
}

echo "Does the empty list work?"
curl -L \
  -X DELETE \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer ${PAT}" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/repos/${OWNER}/${REPO}/pulls/${NUMBER}/requested_reviewers \
  -d '{"reviewers": [], "team_reviewers":["the_senate"]}'
{
  "url": ...<spam>,
```

# Testing?
There's a new unit test. Without the 2nd commit, it fails with:

```
    pulls_reviewers_test.go:181: request Body is {"team_reviewers":["justice-league"]}
        , want {"reviewers":[],"team_reviewers":["justice-league"]}
```

### CODE REVIEW

**Comment by nagl-resourcely** [comment]
Ty for expressing the nit as a diff =)

**Review by gmlewis — APPROVED** [review]
Thank you, @nagl-resourcely !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

**Review by tomfeigin — APPROVED** [review]
LGTM

**Comment by gmlewis** [comment]
Thank you, @tomfeigin !
Merging.

**Pull request merged**
