### PR TITLE
Add IssueTemplate and PullRequestTemplate in ReposCommunityHealth struct

### LINKED ISSUE #956: Add Issue/PR template in CommunityHealthFiles
Thanks to this endpoint : https://developer.github.com/v3/repos/community/

We can get some interesting datas.
Type CommunityHealthFiles contain CodeOfConduct, Contributing, License and Readme files, but not issue template and pull requests files. It might be a good idea to include them into CommunityHealthFiles

### PR DESCRIPTION
**Pull request by joan-saum**
Closes #956

### CODE REVIEW

**Comment by joan-saum** [comment]
@gmlewis I don't understand why the Travis CI build failed

**Comment by gmlewis** [comment]
Did you remember to generate the `github-accessors.go` file?

Please see the CONTRIBUTING.md file for more details.

**Comment by gmlewis** [comment]
```
5. Please run:

    go generate github.com/google/go-github/...
    go test github.com/google/go-github/...
    go vet github.com/google/go-github/...
```

**Comment by joan-saum** [comment]
Ok, my bad. I did it but in the wrong directory. Should be better now

**Pull request merged**
