### PR TITLE
Add SecretScanningAlertEvent Webhook

### LINKED ISSUE #2277: Support "secret_scanning_alert" webhooks and event payloads
Secret scanning has been GA since April 2021 (https://github.blog/changelog/2021-04-01-secret-scanning-for-private-repositories-is-generally-available/) for Advanced Security and since 3.1 in Enterprise.

The webhook payload is documented here
https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#secret_scanning_alert

### PR DESCRIPTION
**Pull request by IainSteers**
Fixes #2277

### CODE REVIEW

**Comment by IainSteers** [comment]
It looks like #2281 introduces the full SecretScanningAlert struct used in the API.

I propose waiting until that merges and then I'll refactor to use it in the webhook payload.

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @IainSteers !
Just a couple minor tweaks, please, for the auto-generated godocs.
Also, please refrain from using force-push in this repo... we squash all commits anyway, and it is easier for the reviewers to see what changed. For more info, please see our CONTRIBUTING.md doc.

**Comment by IainSteers** [comment]
Apologies for the force-push, did it whilst rebasing without realising. I've made the corrections in punctuation.

**Review by gmlewis — APPROVED** [review]
Thank you, @IainSteers!
LGTM.

Awaiting second LGTM/Approval from any other contributor of this repo before merging.

**Review by raynigon — APPROVED** [review]
LGTM

**Comment by gmlewis** [comment]
Thank you, @raynigon !
Merging.

**Pull request merged**
