### PR TITLE
Add pointers to structs in slices

### PR DESCRIPTION
**Pull request by gmlewis**
Since we decided in #180 to standardize using pointers to structs when they appear in slices, and some slices have slipped through code reviews without having pointers, this PR cleans these up.

Fixes: #1100. 

This is a breaking API change.

### CODE REVIEW

**Comment by joebowbeer** [comment]
@gmlewis Why was this breaking change in the API released in v29.0.3? I was expecting v29.0.3 to be interchangeable with v29.0.2

**Comment by gmlewis** [comment]
I apologize... that was a slip on my part.  Someone asked for a new release to be created and I forgot that breaking changes were included.  I don't know how to fix it now, as it seems that once a release is made, it is archived in the mod tools.

To help this situation, I might be able to create a new v30.0.0 release now, but I'm afraid the damage has been done, and I'm sorry about that.

**Comment by joebowbeer** [comment]
My mistake: I don't think this was released to v29.0.3. It is one of the 17 commits *since* v29.0.3

**Comment by joebowbeer** [comment]
@gmlewis However, I am seeing the incompatible master src when I go get v29, which is causing inexplicable type errors to surface. A v30 release would be helpful, and would make it clear that master go.mod is v30 source.

**Comment by gmlewis** [comment]
Alright, in that case I know for a fact that we have a large number of breaking changes between v29 and v30 and I believe one or two outstanding PRs will further break things. I was planning a v30 release would happen really soon in the hopes that the breaking changes would subside for a while (many APIs have been deprecated and changed lately from the v3 API)... so if we could hold off for just a few days, I think it would be the least disruptive for all users of the repo.

I'll try to prod along the outstanding PRs... but I can make no guarantees as to schedule, unfortunately.

**Comment by gmlewis** [comment]
Taking a more detailed look, it appears that #1451 is the only one that is close that should get in before `v30.0.0`.  I need a second LGTM on it, hopefully from @dmitshur but he probably wouldn't mind if another LGTM came in from someone else, since it appears to me that his comments have already been addressed.

**Comment by gmlewis** [comment]
@joebowbeer - here's the plan - one more change is needed in #1451, then we can get #1456 approved by two LGTMs and merged, then we can release `v30.0.0`. Hopefully this can all happen today.

**Pull request merged**
