### PR TITLE
Add support code scanning organizational-level API

### LINKED ISSUE #2588: Support code scanning organizational-level API
GitHub announcement: https://github.blog/changelog/2022-12-01-code-scanning-organization-level-rest-api-is-available-for-public-repositories/

This would be a great PR for any new contributor to this repo or a new Go developer.
All contributions are greatly appreciated!

Feel free to volunteer for any issue and the issue can be assigned to you so that others don't attempt to duplicate the work.

Please check out our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) guide to get started. (In particular, please remember to `go generate ./...` and don't use force-push to your PRs.)

Thank you!

### PR DESCRIPTION
**Pull request by shogohida**
Signed-off-by: Shogo Hida <shogo.hida@gmail.com>

Fixes #2588

### CODE REVIEW

**Review by gmlewis — COMMENTED** [review]
I believe this is the API we are talking about: https://docs.github.com/en/enterprise-cloud@latest/rest/code-scanning?apiVersion=2022-11-28#list-code-scanning-alerts-for-an-organization
which would mean that it needs to support a bunch of query parameters and not add the `id` to the end of the URL.

Please correct me if I'm looking at the wrong endpoint.

If I am looking at the correct endpoint, then you would need to add an `opts` parameter to add query parameters to the `GET` request. There are lots of examples of this in the repo.

**Comment by shogohida** [comment]
@gmlewis 
Thanks for your comment. An `opts` parameter already exists in the function for this endpoint, doesn't it? Correct me if I'm wrong.

https://github.com/google/go-github/blob/master/github/code-scanning.go#L189-L192

**Comment by gmlewis** [comment]
> @gmlewis Thanks for your comment. An `opts` parameter already exists in the function for this endpoint, doesn't it? Correct me if I'm wrong.
> 
> https://github.com/google/go-github/blob/master/github/code-scanning.go#L189-L192

Oh, right!  I missed it in my search the other day. My bad.

Then I think this PR can be completely closed, as the issue is already resolved, correct?

I'm trying to find the endpoint you added:

```go
u := fmt.Sprintf("org/%v/%v/code-scanning/alerts/%v", owner, org, id)
```

and I'm not finding it anywhere in the official documentation... where is it?

**Comment by shogohida** [comment]
Yeah, I think this can be closed.

Because` ListAlertsForOrg` already exists and I wasn't sure what to code, I just copied the endpoint from [here](https://github.com/google/go-github/blob/master/github/code-scanning.go#L247). I thought I needed to create a new function for an organization that isn't in the documentation but my understanding was wrong

**Comment by gmlewis** [comment]
That was totally my fault, @shogohida - I should have seen that this was already implemented.
I apologize.

Closing as already implemented.

**Comment by shogohida** [comment]
No problem! I hope to contribute to another good first issue

**Pull request closed without merging**
