### PR TITLE
Add PreviousAttemptURL, RunAttempt, RunStartedAt field to WorkflowRun

### PR DESCRIPTION
**Pull request by tohjustin**
Add `PreviousAttemptURL`, `RunAttempt`, `RunStartedAt` field to the `WorkflowRun` struct.

Fixes: #2237.

### CODE REVIEW

**Comment by tohjustin** [comment]
I've just signed the CLA, can one of the repository manager trigger a rescan? 😅  Thanks!

**Review by gmlewis — APPROVED** [review]
Thank you, @tohjustin !
LGTM.
Merging.

**Comment by tohjustin** [comment]
Thanks for reviewing this @gmlewis, happy holidays! 🙏🏼

**Comment by gmlewis** [comment]
> Thanks for reviewing this @gmlewis, happy holidays! 🙏🏼

My pleasure!  Merry Christmas and Happy Holidays to you too, @tohjustin !

**Pull request merged**
