### PR TITLE
Make test names consistent

### PR DESCRIPTION
**Pull request by gmlewis**

### CODE REVIEW

**Comment by gmlewis** [comment]
@sagar23sj - would you mind giving me an LGTM+Approval on this one if you agree, please?

**Comment by sagar23sj** [comment]
Sure @gmlewis 
LGTM.

**Review by sagar23sj — APPROVED** [review]

**Comment by sagar23sj** [comment]
There are few files remaining @gmlewis. I have listed them below

- licenses_test.go
- orgs_test.go
- pulls_reviewers_test.go

would you like me to push the commit for remaining files ??

**Comment by gmlewis** [comment]
Sure, @sagar23sj ... Thank you!

**Comment by sagar23sj** [comment]
If it's ok with you and you have'nt already started working, i can raise PR for the remaining ones @gmlewis

**Comment by gmlewis** [comment]
> If it's ok with you and you have'nt already started working, i can raise PR for the remaining ones @gmlewis

Perfect... thank you, @sagar23sj !

**Pull request merged**
