### PR TITLE
Allow create custom repository/organization roles without permission

### PR DESCRIPTION
**Pull request by andriyun**
Changes related to the issue https://github.com/google/go-github/issues/3226

### CODE REVIEW

**Comment by andriyun** [comment]
See a discussion about the approach in the relevant issue https://github.com/google/go-github/issues/3226

**Review by gmlewis — CHANGES_REQUESTED** [review]
So this is much closer, but my point was that we need two _NEW_ endpoints so as to not affect the people who are currently not modifying the permissions (and therefore _need_ the `omitempty`).

We need a new `CreateCustomOrgRoleNoPermissions` and a new `CreateCustomRepoRoleNoPermissions` that both use the "trick" of an inline struct that removes the `omitempty` like you have done here.
The comment for each of these need to clearly state why these two endpoints are needed.

**Comment by andriyun** [comment]
I don't think I understand the need of having separate endpoint.

It is clear for me that method _CreateCustomRepoRole_ will fail if you call it without any of properties of type _CreateOrUpdateCustomRepoRoleOptions_. Which is expected and makes sense after reading GitHub Rest API

However it will also fail when you call it with defined values for each of the properties where empty array is used as value for _Permission_. Which is my case exactly.

The aim of this PR is to fix the bug. While still using the same methods without breaking current API as you requested :)

Taking into account above written, what would be the benefits from having extra endpoint?

**Comment by gmlewis** [comment]
So isn't it true that users will want the `omitempty` when they wish to not _modify_ existing permissions?
Or are you saying that there is never a usage for not sending the `permissions` field?
I'll go read the docs again as well.

I know we have other endpoints where we must differentiate between an omitted field and an empty field, and I thought this was one of those cases.

**Comment by gmlewis** [comment]
This endpoint says that `permissions` is required: https://docs.github.com/en/enterprise-cloud@latest/rest/orgs/custom-roles?apiVersion=2022-11-28#create-a-custom-repository-role

However, this endpoint makes _NO MENTION_ of the `permissions` field: https://docs.github.com/en/rest/orgs/organization-roles?apiVersion=2022-11-28#create-a-custom-organization-role

What's up with that?

**Comment by andriyun** [comment]
> So isn't it true that users will want the omitempty when they wish to not modify existing permissions?

Yes it is true. In this case I would expect _Permission_ property to be _nil_, so condition will return false and parameters would be send untouched.

The intention of the changes is to rewrite type for the case when _Permissions_ property has an empty array as value

**Comment by andriyun** [comment]
> However, this endpoint makes NO MENTION of the permissions field: https://docs.github.com/en/rest/orgs/organization-roles?apiVersion=2022-11-28#create-a-custom-organization-role

This link lead me to: Get all organization roles

If you open this link https://docs.github.com/en/enterprise-cloud@latest/rest/orgs/organization-roles?apiVersion=2022-11-28#create-a-custom-organization-role

You find _permission_ key as required

**Comment by gmlewis** [comment]
OK, so if I'm reading the docs correctly, then the `permissions` field is _ALWAYS_ required, correct?

If so, I truly apologize for chasing you down an incorrect rabbit hole that I created.

So it looks like completely removing the `omitempty` is simply the right choice afterall, agreed?

**Comment by andriyun** [comment]
NP. Glad we clarified the intention here :)

Unfortunatelly type _CreateOrUpdateCustomRepoRoleOptions_ used for both _Create_ (where all the properties are required) and _Update_ where all of them are optional 😀

So we either rewrite API or use tweaks like I suggested in the PR

**Comment by gmlewis** [comment]
OK, now that we've tried all the possibilities, I'll let you decide which you think is most appropriate.
Please let mw know when you want me to take another look.
If it requires breaking the API, then so be it.  If, however, you can avoid it, that would be nice-to-have.

**Comment by gmlewis** [comment]
@andriyun - can you please explain to me how what you have written is _different_ from simply removing the `omitempty` on lines 56 and 64?

I'm honestly having troubles understanding the difference.

**Comment by andriyun** [comment]
Ok, I was wrong in my assumption before. And solution here is way more simpler

**Review by gmlewis — APPROVED** [review]
Thank you, @andriyun !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

**Comment by gmlewis** [comment]
(nit: @andriyun - In the future, please don't use force-push in this repo, as now the history of all the experiments we went through and discussed are now lost and we can't refer to them in case others want to discuss them. Also, we always squash-and-merge in this repo so there is never a concern about bloated history in the final commits.)

**Comment by andriyun** [comment]
Ohhh.. ok, got you. I have previous changes saved in separate branches locally.

Do you want me to add them?

**Comment by gmlewis** [comment]
No, that's OK... if someone in the future wants to dig up what we discussed, we can try and recreate then.  😂 
Thank you for offering, though! 😄

**Review by tomfeigin — APPROVED** [review]
LGTM

**Comment by gmlewis** [comment]
Thank you, @tomfeigin !
Merging.

**Pull request merged**
