### PR TITLE
Add information about release cadence to README.md

### PR DESCRIPTION
**Pull request by gmlewis**
With the recent requests for new releases, it would be nice to provide this FAQ in the README.md.

### CODE REVIEW

**Comment by willnorris** [comment]
are we just doing on-demand releases?  I think the point I was making in #1280 was just about having a more predictable release schedule, not abandoning scheduled releases at all.  That said, you're the one doing the bulk of the lifting here, so it's up to you if you want to try and do scheduled releases.

The most important part is that we set expectations appropriately, which this certainly does if this is the plan going forward.

**Comment by gmlewis** [comment]
Well, it certainly is easier to perform on-demand releases from a maintenance perspective.

If you would prefer scheduled releases, what kind of schedule are you thinking?

**Comment by willnorris** [comment]
4-6 weeks?

**Comment by willnorris** [comment]
or even longer if there's not much new

**Comment by gmlewis** [comment]
OK, sure, let's try that.  I'll close this PR.

**Pull request closed without merging**
