### PR TITLE
Added support for allowing apps to push to protected branches

### LINKED ISSUE #1275: Add support for allowing apps to push to protected branches
Support has just been added to the REST API:

https://developer.github.com/changes/2019-09-05-apps-protected-branches-api/

The main benefit for us will be to give dependabot permissions to auto-merge protected branches.

### PR DESCRIPTION
**Pull request by shibasisp**
fixes #1275

### CODE REVIEW

**Comment by shibasisp** [comment]
@gmlewis Can you please review it?

**Comment by shibasisp** [comment]
@gmlewis thanks for the review. I have modified the codes accordingly.

> Additionally, for this to fully resolve #1275, one of the existing `PUT` endpoints needs to have a new `restrictions` field to be added to the request. If you could address that as well, that would be great.

I think, I have already modified the already existing PUT endpoint(`UpdateBranchProtection`) by adding [this line](https://github.com/google/go-github/pull/1283/files#diff-49ba3de83fa99f3d8bae2ece519a449fR795) and [this line](https://github.com/google/go-github/pull/1283/files#diff-49ba3de83fa99f3d8bae2ece519a449fR808). Isn't it?

**Comment by shibasisp** [comment]
@gauntface can you please review it?

**Comment by gmlewis** [comment]
Thank you, @wesleimp !
Merging.

**Pull request merged**
