### PR TITLE
fix references to webhook types

### PR DESCRIPTION
**Pull request by iam-veeramalla**
Fixes: #2222.

### CODE REVIEW

**Review by gmlewis — APPROVED** [review]
Thank you, @iam-veeramalla !
LGTM.
Merging.

**Comment by gmlewis** [comment]
@googlebot update label

**Comment by iam-veeramalla** [comment]
> @googlebot update label

@gmlewis is there an issue with the bot ? Do I need to do something manually?

**Comment by gmlewis** [comment]
@iam-veeramalla - no, you don't need to do anything.
I was just hoping to get its attention to add the "CLA: yes" label to the issue just to avoid any future confusion.

@googlebot already approved the PR, but it neglected to add the label.  I'll give it a little more time... and see if it wakes up.

**Comment by gmlewis** [comment]
OK, @googlebot, I gave you your chance.  I'll add the label myself.

**Comment by gmlewis** [comment]
> frowning_face Sorry, but only Googlers may change the label `cla: yes`.

Ah, right.  I remember that block of code.  :joy:

Too bad we didn't allow Xooglers to change the label.  Oh well.

**Comment by iam-veeramalla** [comment]
looks like the bot is playing around :p with us @gmlewis

**Pull request merged**
