### PR TITLE
Add BranchProtectionRuleEvent Installation field

### PR DESCRIPTION
**Pull request by nyarly**
Although it isn't yet documented at github, the BranchProtectionRuleEvent
includes an `installation` field which is crucial for letting Apps reacting to it
to authenticate their requests.

This PR adds that field the event type, along with an accessor for it.

Fixes: #2214.

### CODE REVIEW

**Comment by nyarly** [comment]
I've just added a CLA for this project.

**Comment by gmlewis** [comment]
@googlebot rescan

**Comment by gmlewis** [comment]
Thank you, @nyarly !
Please run `go generate ./...` and push (not force-push) the changed files to this PR, and the tests should then pass.
Hopefully @googlebot will also see your signed CLA by then.

**Review by gmlewis — APPROVED** [review]
Thank you, @nyarly !
LGTM.

Merging.

**Pull request merged**
