### PR TITLE
Add support for deleting an org

### LINKED ISSUE #2726: Add support for deleting an organization.
A new REST endpoint was added to delete an organization at `/orgs/{org}'`. The documentation doesn't seem to have gone live quite yet but I'll update the issue as soon as I see it. In the meantime the endpoint can be evoked like:

`curl -X DELETE https://api.github.com/orgs/:org`

Now with [documentation](https://docs.github.com/en/rest/orgs/orgs?apiVersion=2022-11-28#delete-an-organization)!

### PR DESCRIPTION
**Pull request by tjcorr**
Fixes: #2726.

### CODE REVIEW

**Review by gmlewis — CHANGES_REQUESTED** [review]
~Since we use only a single client for all APIs in this repo and therefore we don't have the stutter problem, could we please clarify the method name by calling it `DeleteOrg`?~

**Comment by tjcorr** [comment]
> Since we use only a single client for all APIs in this repo and therefore we don't have the stutter problem, could we please clarify the method name by calling it `DeleteOrg`?

I was just matching the format I saw in other areas like: https://github.com/google/go-github/blob/master/github/repos.go#L590-L601

**Review by gmlewis — APPROVED** [review]
Thank you, @tjcorr !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

**Review by valbeat — APPROVED** [review]
LGTM!

**Pull request merged**
