### PR TITLE
Always send 'checks' field when creating branch protection

### LINKED ISSUE #2467: Error when creating branch protection
Since we updated our code to use the latest version of this library, we can't create a branch protection that requires branches to be up to date before merging but don't require any status checks:

```go
func (r *RepoSettings) protectionRequestOptions() *github.ProtectionRequest {
	return &github.ProtectionRequest{
		EnforceAdmins: r.EnforceAdmins,
		RequiredPullRequestReviews: &github.PullRequestReviewsEnforcementRequest{
			DismissStaleReviews:          r.DismissStaleReviews,
			RequiredApprovingReviewCount: r.RequiredApprovingReviewCount,
			RequireCodeOwnerReviews:      r.RequireCodeOwnerReviews,
		},
		RequiredStatusChecks: &github.RequiredStatusChecks{
			Strict: true,
		},
	}
}
```

The above results in an error:

```
PUT https://api.github.com/repos/****/****/branches/main/protection: 422 Invalid request.

No subschema in "anyOf" matched.
No subschema in "oneOf" matched.
Not all subschemas of "allOf" matched.
For 'anyOf/1', {"strict"=>true} is not a null. []
```

Such rule is possible to be created from the UI:
image

This is also affecting the Github Terraform provider: https://github.com/integrations/terraform-provider-github/issues/1147

### PR DESCRIPTION
**Pull request by luisdavim**
Fixes #2467

### CODE REVIEW

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @luisdavim .
Could you please add a unit test demonstrating that this field is indeed sent when empty as a means of documenting that we explicitly wish to send it in all cases?

**Comment by luisdavim** [comment]
@gmlewis I've added a new test case for this scenario, where we set strict branch protection checks with an empty set of checks but, whilst looking at the tests, I found some inconsistency between the inputs and the mocks of the existing tests so I also fixed those in the same commit, I hope that's ok.

**Review by gmlewis — APPROVED** [review]
Thank you, @luisdavim !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

**Review by raynigon — APPROVED** [review]
LGTM

**Comment by gmlewis** [comment]
Thank you, @raynigon !
Merging.

**Pull request merged**
