### PR TITLE
Add test cases for JSON resource marshaling

### PR DESCRIPTION
**Pull request by sagar23sj**
Resources Covered :

- GetAuditLogOptions
- HookConfig
- AuditEntry

Helps with issue: #55

### CODE REVIEW

**Review by gmlewis — APPROVED** [review]
Thank you, @sagar23sj !
LGTM.

Awaiting second LGTM before merging.

**Comment by gmlewis** [comment]
@googlebot - please do your thing.

**Comment by gmlewis** [comment]
Thanks.  :smile:

**Comment by sagar23sj** [comment]
haha 🤣

**Review by Parker77 — APPROVED** [review]
LGTM.

**Pull request merged**
