### PR TITLE
Implement support for repository visibility parameter

### PR DESCRIPTION
**Pull request by patrickmarabeas**
Implements support for specifying a repositories visibility. It can be
one of public, private or internal (if the organization is associated
with an enterprise account).

The associated preview header (nebula) has also been added.

Resolves: #1470

### CODE REVIEW

**Comment by patrickmarabeas** [comment]
What is the release cadence for this project - I would like to put this to use in the Github Terraform Provider ASAP!

**Comment by gmlewis** [comment]
We used to do a semver (major, minor, patch) release on each merged PR, but that got way too extreme... so now we release on demand.  I can make a new release after this PR is merged.

**Comment by patrickmarabeas** [comment]
That would be great - thanks @gmlewis!

**Comment by gmlewis** [comment]
Thank you, @wesleimp!
Merging, then making a minor release.

**Comment by gmlewis** [comment]
@patrickmarabeas - Version `v30.1.0` has now been released at your request.

**Pull request merged**
