### PR TITLE
Add test for resource JSON marshaling - ActionVariable

### PR DESCRIPTION
**Pull request by ResamVi**
Hello,

this is just another trivial test adding to the 10 year old issue. I hope there is still demand for this.

Helps #55

### CODE REVIEW

**Comment by gmlewis** [comment]
Thank you, @ResamVi - is this for hacktoberfest credit?
If so, I'll label it as accepted.

**Comment by gmlewis** [comment]
Please make sure unit tests pass locally first by running `go test ./...`.

**Comment by ResamVi** [comment]
Whoops, that was a tad too hasty of me :see_no_evil: . Should be fixed now.

This is indeed for hacktoberfest so I would happily take the accept label :)

**Review by gmlewis — APPROVED** [review]
Thank you, @ResamVi !
LGTM.
Merging.

**Pull request merged**
