### PR TITLE
Add disabled bit to Organization struct.

### PR DESCRIPTION
**Pull request by rspier**

### CODE REVIEW

**Comment by gmlewis** [comment]
Wow, you all are awesome!
Hi and thank you too all my friends!
😁

**Comment by rspier** [comment]
We miss you Glenn!

**Comment by gmlewis** [comment]
Thanks, Robert. I miss you guys too!
You should take a team trip and come visit! 😁

**Comment by willnorris** [comment]
We do have quarterly face-to-face meetings.... maybe we need to do one in Orlando 😄

**Comment by rspier** [comment]
Glenn and Mickey, that's a winning combination!

**Pull request merged**
