### PR TITLE
Don't update the ratelimits if we got a response from a cache

### PR DESCRIPTION
**Pull request by Jille**
The recommended cache, https://github.com/gregjones/httpcache, returns
an X-From-Cache: 1 header whenever it serves a response from the cache.

Cached responses might include (possibly stale) ratelimit headers, which
we would've already processed in the past.

### CODE REVIEW

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @Jille !
Can you please add a unit test that demonstrates this change in functionality?

Also, once you sign the CLA, we can move forward with this PR.

**Comment by Jille** [comment]
Thanks for the quick review :)

Added tests, rebased to master, signed the CLA.

**Review by gmlewis — APPROVED** [review]
Thank you, @Jille !
LGTM.

Awaiting second LGTM from any other contributor to this repo before merging.

**Review by raynigon — APPROVED** [review]
LGTM

**Comment by gmlewis** [comment]
Thank you, @raynigon !
Merging.

**Pull request merged**
