### PR TITLE
Add `GetAssignees` to `Issue`

### PR DESCRIPTION
**Pull request by DazWilkin**
code|test copied from `IssueRequest`

### CODE REVIEW

**Comment by gmlewis** [comment]
Please read through CONTRIBUTING.md.
These files are auto-generated and should not be edited.

**Comment by gmlewis** [comment]
Closing PR.

**Comment by DazWilkin** [comment]
Apologies!

**Comment by gmlewis** [comment]
No apology necessary!  I know it can be very confusing.  Thanks.

**Pull request closed without merging**
