### PR TITLE
New repo payload

### PR DESCRIPTION
**Pull request by pzurek**
This PR fixes and issue caused most likely by a change in the PushEvent webhook payload structure. Looking at the payload of a recently received PushEvent webhook, it looks like the organization object from inside the repo object was moved a level up and replaced by a string containing the name. Sample payload below.

```json
{
  "ref": "refs/heads/master",
  "before": "09860b4cae44dd33c28af8af36728a9dc5345719",
  "after": "b83f80529c36e97ae50520c9f55d778b976cef10",
  "created": false,
  "deleted": false,
  "forced": false,
  "base_ref": null,
  "compare": "https://github.com/redacted-org-name/redacted-repo-name/compare/09860b4cae44...b83f80529c36",
  "commits": [
    {
      "id": "b83f80529c36e97ae50520c9f55d778b976cef10",
      "distinct": true,
      "message": "#479 adding draft",
      "timestamp": "2016-01-22T17:08:57+13:00",
      "url": "https://github.com/redacted-org-name/redacted-repo-name/commit/b83f80529c36e97ae50520c9f55d778b976cef10",
      "author": {
        "name": "Mikey Jarvis",
        "email": "mikey@redacted-email-domain",
        "username": "mikjarv"
      },
      "committer": {
        "name": "Mikey Jarvis",
        "email": "mikey@redacted-email-domain",
        "username": "mikjarv"
      },
      "added": [
        "Accurately Calculating COGS.md"
      ],
      "removed": [],
      "modified": []
    }
  ],
  "head_commit": {
    "id": "b83f80529c36e97ae50520c9f55d778b976cef10",
    "distinct": true,
    "message": "#479 adding draft",
    "timestamp": "2016-01-22T17:08:57+13:00",
    "url": "https://github.com/redacted-org-name/redacted-repo-name/commit/b83f80529c36e97ae50520c9f55d778b976cef10",
    "author": {
      "name": "Mikey Jarvis",
      "email": "mikey@redacted-email-domain",
      "username": "mikjarv"
    },
    "committer": {
      "name": "Mikey Jarvis",
      "email": "mikey@redacted-email-domain",
      "username": "mikjarv"
    },
    "added": [
      "Accurately Calculating COGS.md"
    ],
    "removed": [],
    "modified": []
  },
  "repository": {
    "id": 20011311,
    "name": "redacted-repo-name",
    "full_name": "redacted-org-name/redacted-repo-name",
    "owner": {
      "name": "redacted-org-name",
      "email": "support@redacted-email-domain"
    },
    "private": true,
    "html_url": "https://github.com/redacted-org-name/redacted-repo-name",
    "description": "A repository used to work for version control of our Zendesk help centre articles",
    "fork": false,
    "url": "https://github.com/redacted-org-name/redacted-repo-name",
    "forks_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/forks",
    "keys_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/teams",
    "hooks_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/hooks",
    "issue_events_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/issues/events{/number}",
    "events_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/events",
    "assignees_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/assignees{/user}",
    "branches_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/branches{/branch}",
    "tags_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/tags",
    "blobs_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/languages",
    "stargazers_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/stargazers",
    "contributors_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/contributors",
    "subscribers_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/subscribers",
    "subscription_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/subscription",
    "commits_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/contents/{+path}",
    "compare_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/merges",
    "archive_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/downloads",
    "issues_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/issues{/number}",
    "pulls_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/labels{/name}",
    "releases_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/releases{/id}",
    "deployments_url": "https://api.github.com/repos/redacted-org-name/redacted-repo-name/deployments",
    "created_at": 1400655763,
    "updated_at": "2016-01-13T03:42:29Z",
    "pushed_at": 1453435743,
    "git_url": "git://github.com/redacted-org-name/redacted-repo-name.git",
    "ssh_url": "git@github.com:redacted-org-name/redacted-repo-name.git",
    "clone_url": "https://github.com/redacted-org-name/redacted-repo-name.git",
    "svn_url": "https://github.com/redacted-org-name/redacted-repo-name",
    "homepage": null,
    "size": 29946,
    "stargazers_count": 4,
    "watchers_count": 4,
    "language": "CSS",
    "has_issues": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 0,
    "mirror_url": null,
    "open_issues_count": 32,
    "forks": 0,
    "open_issues": 32,
    "watchers": 4,
    "default_branch": "master",
    "stargazers": 4,
    "master_branch": "master",
    "organization": "redacted-org-name"
  },
  "pusher": {
    "name": "mikjarv",
    "email": "mikey@redacted-email-domain"
  },
  "organization": {
    "login": "redacted-org-name",
    "id": 1250541,
    "url": "https://api.github.com/orgs/redacted-org-name",
    "repos_url": "https://api.github.com/orgs/redacted-org-name/repos",
    "events_url": "https://api.github.com/orgs/redacted-org-name/events",
    "members_url": "https://api.github.com/orgs/redacted-org-name/members{/member}",
    "public_members_url": "https://api.github.com/orgs/redacted-org-name/public_members{/member}",
    "avatar_url": "https://avatars.githubusercontent.com/u/1250541?v=3",
    "description": ""
  },
  "sender": {
    "login": "mikjarv",
    "id": 10819429,
    "avatar_url": "https://avatars.githubusercontent.com/u/10819429?v=3",
    "gravatar_id": "",
    "url": "https://api.github.com/users/mikjarv",
    "html_url": "https://github.com/mikjarv",
    "followers_url": "https://api.github.com/users/mikjarv/followers",
    "following_url": "https://api.github.com/users/mikjarv/following{/other_user}",
    "gists_url": "https://api.github.com/users/mikjarv/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/mikjarv/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/mikjarv/subscriptions",
    "organizations_url": "https://api.github.com/users/mikjarv/orgs",
    "repos_url": "https://api.github.com/users/mikjarv/repos",
    "events_url": "https://api.github.com/users/mikjarv/events{/privacy}",
    "received_events_url": "https://api.github.com/users/mikjarv/received_events",
    "type": "User",
    "site_admin": false
  }
}
```

### CODE REVIEW

**Comment by pzurek** [comment]
Well, actually, it looks like the payload of the webhook is not consistent with the payload of GET on the `/repos` endpoint. It may be necessary to add a separate, push event specific repo struct.

**Comment by willnorris** [comment]
sadly this has been broken for a while (see #131).  This seems like as good a fix as any, but it makes me very sad that we have to add an entirely new type for one single field :cry:

**Comment by pzurek** [comment]
My feelings exactly but need to get the job done. :-)
Weird that @github let's such inconsistencies sneak in.

**Comment by willnorris** [comment]
merged as d722750

**Pull request closed without merging**
