### PR TITLE
Add support to sync a fork branch with the upstream repository.

### LINKED ISSUE #2335: Support "Sync a fork branch with the upstream repository"
API doc here: https://docs.github.com/en/rest/reference/branches#sync-a-fork-branch-with-the-upstream-repository.

### PR DESCRIPTION
**Pull request by lkxed**
Resolved #2335 

Thanks for this opportunity.

### CODE REVIEW

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @lkxed !
This is looking great, but instead of creating two new files, would you mind adding your code to the existing `repos_merging.go` and `repos_merging_test.go` files?
I think both are small enough and related enough to live in the same file.

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @lkxed !
Just one minor renaming tweak, please, then I think we will be ready for a second LGTM before merging.

**Comment by lkxed** [comment]
@gmlewis I have changed the names. :)

**Review by gmlewis — APPROVED** [review]
Thank you, @lkxed !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

**Review by raynigon — APPROVED** [review]
LGTM

**Comment by gmlewis** [comment]
> LGTM

Thank you, @raynigon !
Merging.

**Pull request merged**
