### PR TITLE
Add support for the security and analysis webhook event

### PR DESCRIPTION
**Pull request by byronwolfman**
Fixes https://github.com/google/go-github/issues/2861

Adds support for the [Security and Analysis webhook event](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#security_and_analysis) which fires whenever security and analysis features are enabled or disabled for a repository.

* [x] Ran `go generate`
* [x] Ran `go test`
* [x] Ran `go vet`
* [x] Signed CLA

### CODE REVIEW

**Review by gmlewis — APPROVED** [review]
Thank you, @byronwolfman !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

**Comment by byronwolfman** [comment]
> Thank you, @byronwolfman ! LGTM.
> 
> Awaiting second LGTM+Approval from any other contributor to this repo before merging.

Thanks, sounds good! And thanks for the clear contributing docs that made it possible to put this together. 🙏 💯

**Comment by gmlewis** [comment]
> Thanks, sounds good! And thanks for the clear contributing docs that made it possible to put this together. 🙏 💯

Thank _YOU_ for reading it!  It would be nice if every PR author read it!!! :joy:

**Comment by byronwolfman** [comment]
Gently tagging @jporzucek for review as I see you've done some recent work on security and analysis APIs. 🙏

**Comment by gmlewis** [comment]
Thank you, @jporzucek !
Merging.

**Comment by gmlewis** [comment]
cc: @evankanderson - this will also affect #2865. Sorry about that.

**Pull request merged**
