### PR TITLE
removed authorization preview header

### PR DESCRIPTION
**Pull request by JRonak**
for #464

### CODE REVIEW

**Comment by gmlewis** [comment]
Thank you, @JRonak !  I can change it in this PR when I merge, but in the future you will want to write "Fixes #464." since that is a special string that GitHub detects and takes action on.

See https://help.github.com/articles/closing-issues-via-commit-messages/#closing-an-issue-in-the-same-repository for more information.

LGTM.  Awaiting second LGTM before merging.

**Comment by JRonak** [comment]
thanks @gmlewis ,I will keep that in mind.

**Comment by gmlewis** [comment]
Thank you, @JRonak and @shurcooL !
Merging.

**Comment by gmlewis** [comment]
Integrated in https://github.com/google/go-github/commit/54943985871d3b59053804af48b8347a3c232938

**Pull request closed without merging**
