### PR TITLE
Change create fork options from url param to body param

### LINKED ISSUE #2489: RepositoryCreateForkOptions is should be body parameters
Hi Team!
RepositoryCreateForkOptions is not working. because it is not url params but body params. 
[docs.github.com/en/rest/repos/forks#create-a-fork](https://docs.github.com/en/rest/repos/forks#create-a-fork)

Sorry I didn't realize this when I added it before.

I will create a pull request for this issue. 
Thanks.

### PR DESCRIPTION
**Pull request by valbeat**
resolves #2489

### CODE REVIEW

**Review by gmlewis — APPROVED** [review]
Thank you, @valbeat !
LGTM.

Awaiting second LGTM from any other contributor to this repo before merging.

**Comment by aptattack** [comment]
should be pass

**Comment by TruRelax** [comment]
It's been blocked for weeks 😢

**Comment by gmlewis** [comment]
> It's been blocked for weeks 😢

This repo depends on volunteers to contribute both code and code reviews to move it forward. If you are a contributor to this repo, please feel free to perform a code review and LGTM+Approval if you agree with this change.

**Review by raynigon — APPROVED** [review]
LGTM

Sorry for the late review

**Comment by gmlewis** [comment]
> LGTM
> 
> @gmlewis Sorry for the late review, feel free to mention me if a review is needed.

Thank you, @raynigon , and no worries!
Merging.

**Comment by valbeat** [comment]
Thanks for review!

**Pull request merged**
