### PR TITLE
Add missing fields to Timeline

### PR DESCRIPTION
**Pull request by devfd**

### CODE REVIEW

**Comment by devfd** [comment]
@googlebot I signed it!

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @devfd .
Please make sure to run `go generate ./...` and push (not force-push) the changes to the PR.
See CONTRIBUTING.md for more details.

**Comment by devfd** [comment]
my bad, thanks @gmlewis

**Review by gmlewis — APPROVED** [review]
Thank you, @devfd !
LGTM.
Merging.

**Pull request merged**
