### PR TITLE
Add dependabot alert update endpoint

### LINKED ISSUE #2922: Missing function to update dependabot alerts
Reading [this file](https://github.com/google/go-github/blob/fd33b81221685302178ba197dbabe71326ca9051/github/dependabot_alerts.go
) there is no reference to a function to [Update a Dependabot Alerts](https://docs.github.com/en/rest/dependabot/alerts?apiVersion=2022-11-28#update-a-dependabot-alert
)

I would like to implement it but I am opening an issue first to ask if there is any other way to do it that I am currently missing.

### PR DESCRIPTION
**Pull request by mcollao-hc**
Adds support for https://docs.github.com/en/rest/dependabot/alerts?apiVersion=2022-11-28#update-a-dependabot-alert.

Closes #2922. This is also a dupe of #2955, which hasn't seen action in a few weeks and had build errors.

### CODE REVIEW

**Comment by gmlewis** [comment]
Thank you, @mcollao-hc - I apologize for the delay in taking a look at this.

Please perform step 4 in CONTRIBUTING.md and push the results to this PR.

**Comment by mcollao-hc** [comment]
No worries, thanks for the review. Pushed the files created from running the script.

**Comment by gmlewis** [comment]
Did you run both `./script/generate.sh` and `./script/lint.sh` ?

**Comment by gmlewis** [comment]
I ask because we have a new metadata field required in the docs for each endpoint (that I believe should be updated for you) that is missing.

**Comment by mcollao-hc** [comment]
Ok think I got it. Had to rebase to pick up the new requirements and added the metadata field to the `UpdateAlert` function since it wasn't being added automatically.

**Review by WillAbides — APPROVED** [review]

**Comment by gmlewis** [comment]
Thank you, @WillAbides !
Merging.

**Pull request merged**
