### PR TITLE
fix api preview header, missing :

### PR DESCRIPTION
**Pull request by jurgenweber**
so then the api previews actually work. :)

### CODE REVIEW

**Comment by jurgenweber** [comment]
@googlebot I signed it!

**Comment by jurgen-weber-deltatre** [comment]
considering all the failing CI, this doesn't seem to be the only place/thing I need to update but it is also making me second guess that this is the solution... Will await further input/thoughts.

**Comment by gmlewis** [comment]
> so then the api previews actually work. :)

I'm sorry, I don't understand why this change is necessary.  This repo has been using custom preview headers for years now and they have been working well up to this point. Could you please explain what you saw that caused you to write this PR?

Also, you should be able to run "go test ./..." locally to make sure the unit tests pass.

**Comment by jurgen-weber-deltatre** [comment]
> I'm sorry, I don't understand why this change is necessary. This repo has been using custom preview headers for years now and they have been working well up to this point. 

Yeha, I agree.. Seems weird to me.

> Could you please explain what you saw that caused you to write this PR?

https://github.com/google/go-github/pull/1786#issuecomment-768662735

It was a long story to get to this point, but I feel there is some more to it. I started with using the terraform-provider-github and in the end I can not make internal repos using the provider. I have subsequently ended up here. I started replicating the provider commands with curl commands to ID what is going on.

The beginings of my journey are here; https://github.com/integrations/terraform-provider-github/issues/662

If it isn't the headers, then I am not sure to why when using TF this fails.

GitHub support then pointed me to the concept of the API reviews and I noticed the string difference, using CURL the api call fails without a colon.

> Also, you should be able to run "go test ./..." locally to make sure the unit tests pass.

Ok

**Comment by jurgen-weber-deltatre** [comment]
Just a follow up; I tried this locally (found some time this morning):

https://github.com/jurgenweber/go-github/blob/master/example/orgnewrepo/main.go

this works, so the problem is else wehre.

Thanks

**Comment by jurgenweber** [comment]
I found it; https://github.com/integrations/terraform-provider-github/pull/680

**Pull request closed without merging**
