### PR TITLE
Update PingEvent type

### PR DESCRIPTION
**Pull request by pecigonzalo**
The `ping` event has changed or is different than what is declared in the current
code. Updating it to match https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#ping.

Related: https://github.com/google/go-github/pull/2018

### CODE REVIEW

**Comment by pecigonzalo** [comment]
@gmlewis I found https://github.com/octokit/webhooks and I was trying to actually generate the structs from the schemas or interfaces there. I have not been super successful so far as some of the generated types/interfaces are not appropriate for usage here, but I think it could be a more sustainable way to create these types.

As a separate point, I could not find the diff of the events for Webhooks and the Events API to ensure Im not breaking one or the other.

**Review by Oleksandr-prog — APPROVED** [review]

**Review by Oleksandr-prog — APPROVED** [review]

**Review by Oleksandr-prog — APPROVED** [review]

**Review by Oleksandr-prog — APPROVED** [review]

**Comment by gmlewis** [comment]
@pecigonzalo - this PR is still marked as a "work in progress"... are you ready for review? If so, could you please click the "Ready for review" button?

**Comment by pecigonzalo** [comment]
@gmlewis I left it was draft due to https://github.com/google/go-github/pull/2023#issuecomment-894817819 AFAIR.

**Comment by gmlewis** [comment]
> @gmlewis I left it was draft due to [#2023 (comment)](https://github.com/google/go-github/pull/2023#issuecomment-894817819) AFAIR.

OK. How do you suggest that we proceed with this PR?
What will enable us to move forward with it?

**Comment by pecigonzalo** [comment]
I think this is the key part

> As a separate point, I could not find the diff of the events for Webhooks and the Events API to ensure Im not breaking one or the other.

Particularly Im concerned due to the removal of `GetInstallation` and the overall `Installation` field.

---

The generation would be ideal, so we can more easily keep this up to date, but it could be completely separate.

**Comment by pecigonzalo** [comment]
I'll do that

**Comment by pecigonzalo** [comment]
@gmlewis Ill close this for now as I've struggled a bit to find time for it, ill re-open once its ready.

**Pull request closed without merging**
