### PR TITLE
Add support for list Code Scan Alerts by Org

### PR DESCRIPTION
**Pull request by AbbanMustafa**
Provide functionality for querying Code Scan Alerts by Github Org. As well as support a Repository field within each Alert object.

### CODE REVIEW

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @AbbanMustafa , but it looks like your unit tests are not passing yet.

**Review by gmlewis — APPROVED** [review]
Thank you, @AbbanMustafa !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

**Review by ganeshkumarsv — APPROVED** [review]
LGTM

**Comment by gmlewis** [comment]
Thank you, @ganeshkumarsv !
Merging.

**Comment by gmlewis** [comment]
> @gmlewis Thanks! When can I expect a new version to be released?

Well, we just released v44 so usually we release every 30-60 days or so, but there are a few options...

You could import this version directly by the commit hash that includes this change or we could make a minor release probably next Sunday or Monday when I get back to my computer.

**Pull request merged**
