### PR TITLE
Remove graduated GitHub v3 API preview headers

### PR DESCRIPTION
**Pull request by vikkyomkar**
This PR addresses below issue
#1616

### CODE REVIEW

**Comment by vikkyomkar** [comment]
@gmlewis can we get a 2nd review on this ?

**Comment by gmlewis** [comment]
@wesleimp - do you have time for a review?
I believe we have a few outstanding PRs to look at when you have time.
Thank you!

**Review by wesleimp — APPROVED** [review]
Thank you, @vikkyomkar 
LGTM 👌🏼

**Comment by gmlewis** [comment]
Thank you, @wesleimp !
Merging.

**Pull request merged**
