### PR TITLE
issue-1346: support new fields in Organization struct

### PR DESCRIPTION
**Pull request by rajatjindal**

### CODE REVIEW

**Comment by rajatjindal** [comment]
I'll make those changes tonight.

**Comment by rajatjindal** [comment]
I've made the changes. the custom header test was already there for Get operation.

**Comment by gmlewis** [comment]
Thank you, @rajatjindal.  For future reference, please do not use force-push on PRs for this repo, as it makes it more difficult for reviewers to see what changed since the last code review.

**Comment by rajatjindal** [comment]
sure, I will keep that in mind. thanks

**Comment by gmlewis** [comment]
Thank you, @wesleimp!
Merging.

**Pull request merged**
