### PR TITLE
Update URLs

### PR DESCRIPTION
**Pull request by gmlewis**
In preparation for the upcoming release of `v33.0.0`, this PR updates the URLs to match the latest website documentation.

### CODE REVIEW

**Comment by gmlewis** [comment]
@erikkn  - feel free to approve this PR to help expedite the release. :smile:

**Review by erikkn — APPROVED** [review]
A lot of changes, but looks like you used something like sed and tests are passing, so LGTM :). Thanks @gmlewis !

**Comment by gmlewis** [comment]
Thank you, @erikkn.
Keeping the URLs up-to-date is fortunately fairly automated using the `update-urls` program in this repo, but it does typically generate huge PRs that are mostly noise, unfortunately.

Yet, I find that working URLs is tremendously helpful both for development and for debugging problems, so I like to keep them as current as possible even though the GitHub team is constantly updating the docs.

**Comment by erikkn** [comment]
Awesome, makes sense, thanks for the explanation

**Pull request merged**
