### PR TITLE
Add GenerateEnterpriseJITConfig

### PR DESCRIPTION
**Pull request by gabriel-samfira**
With version 3.10 of GitHub Enterprise server, the new just-in-time runner configuration is available for enterprises.

See: https://docs.github.com/en/enterprise-cloud@latest/rest/actions/self-hosted-runners?apiVersion=2022-11-28#create-configuration-for-a-just-in-time-runner-for-an-enterprise

CC: @mkulke

### CODE REVIEW

**Review by gmlewis — APPROVED** [review]
Thank you, @gabriel-samfira !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

**Comment by gmlewis** [comment]
@WillAbides - do you have time for a code review on this one?
I apparently forgot to add the "NeedsReview" label on it a couple weeks ago - sorry about that, @gabriel-samfira !

**Comment by gabriel-samfira** [comment]
No worries at all @gmlewis !

**Review by WillAbides — APPROVED** [review]

**Comment by gmlewis** [comment]
Thank you, @WillAbides !
Merging.

**Pull request merged**
