### PR TITLE
Add List Installation Requests API

### PR DESCRIPTION
**Pull request by abhijit-hota**
The PR adds support for [listing installation requests for the authenticated app](https://docs.github.com/en/rest/apps/apps?apiVersion=2022-11-28#list-installation-requests-for-the-authenticated-app).

- [x] Feature addition
- [x] Added Tests
- [x] Run the essential scripts for linting, generation etc.

### CODE REVIEW

**Comment by abhijit-hota** [comment]
Signed CLA and rescanned.

**Review by gmlewis — APPROVED** [review]
Thank you, @abhijit-hota !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

**Comment by abhijit-hota** [comment]
Thanks, @gmlewis. I see that the coverage has decreased somehow. Can I do anything about it?

**Comment by gmlewis** [comment]
> Thanks, @gmlewis. I see that the coverage has decreased somehow. Can I do anything about it?

I don't think so, because it is harder to test the endpoints that take no parameters in the URL itself... as we can't corrupt it as easily... so I'm not worried about the dropping code coverage in this case.

Thank you for checking, though, @abhijit-hota !  It is appreciated. ❤️

**Review by WillAbides — APPROVED** [review]

**Comment by gmlewis** [comment]
Thank you, @WillAbides !
Merging.

**Comment by abhijit-hota** [comment]
@gmlewis Thank you for the prompt review and merge!

Is there any tentative release date for this?

**Comment by gmlewis** [comment]
> @gmlewis Thank you for the prompt review and merge!
> 
> Is there any tentative release date for this?

It might be nice to get #2937, #2948, and #2949 merged before cutting the new release.
If you feel like moving the process along by contributing to code reviews, that would be greatly appreciated.

**Comment by abhijit-hota** [comment]
Hi @gmlewis, I see that the above PRs have been merged!

We're currently using the master branch and would prefer to shift to a pinned release. 

Thanks!

**Comment by abhijit-hota** [comment]
Thanks for the quick response again, @gmlewis!

**Pull request merged**
