### PR TITLE
Update active committers struct

### PR DESCRIPTION
**Pull request by ganeshkumarsv**
Update active committers struct to include additional attributes.

### CODE REVIEW

**Comment by ganeshkumarsv** [comment]
@gmlewis can you please take a look when you have time? I added all the introduced attributes into the test case, I'm not sure why the code coverage still fails.

**Comment by gmlewis** [comment]
> @gmlewis can you please take a look when you have time? I added all the introduced attributes into the test case, I'm not sure why the code coverage still fails.

Thank you, @ganeshkumarsv !
Yes, we currently have an issue with CodeCov where we need the token in this repo to be updated for it to work again.
For details, see: https://github.com/google/go-github/pull/3221

**Review by gmlewis — APPROVED** [review]
Thank you, @ganeshkumarsv !
LGTM.
Merging.

**Comment by gmlewis** [comment]
> Thank you for merging @gmlewis 🙇. Is it possible to create a new release?

Our next release will probably be in a couple weeks.

**Comment by gmlewis** [comment]
This has now been released: https://github.com/google/go-github/releases/tag/v65.0.0

**Pull request merged**
