### PR TITLE
Expose event message headers, introduce a new way to read the body from an `io.Reader`

### PR DESCRIPTION
**Pull request by m19c**
This pull request introduces the changes described in #1944.

- Expose the constants `sha1SignatureHeader`, `sha256SignatureHeader`, `eventTypeHeader` and `deliveryIDHeader`
- Introduce a new public function called `ValidatePayloadFromBody` to read the body directly from an `io.Reader` rather than a `http.Request`.

The changes described enables the possibility to use `go-github` even with http libraries like `fiber` or `fasthttp`.

Example A:

```go
app.Get(func(ctx *fiber.Ctx) error {
	signature := ctx.Get(github.SHA256SignatureHeader)
	if signature == "" {
		signature = ctx.Get(github.SHA1SignatureHeader)
	}
	
	payload := ctx.Body()
	err := github.ValidateSignature(signature, payload, mySecretToken)
	// ...

	event, err := github.ParseWebHook(ctx.Get(github.EventTypeHeader), payload)
	// ...
})
```

Example B:

```go
app.Get(func(ctx *fiber.Ctx) error {
	signature := ctx.Get(github.SHA256SignatureHeader)
	if signature == "" {
		signature = ctx.Get(github.SHA1SignatureHeader)
	}
	
	payload, err := github.ValidatePayloadFromBody(ctx.Get("Content-Type"), ctx.Context().RequestBodyStream(), signature, mySecretToken)
	// ...

	event, err := github.ParseWebHook(ctx.Get(github.EventTypeHeader), payload)
	// ...
})
```

### CODE REVIEW

**Comment by m19c** [comment]
@googlebot I signed it!

**Review by gmlewis — APPROVED** [review]
Thank you, @m19c !
LGTM.

Awaiting second LGTM before merging.

**Comment by gmlewis** [comment]
@m19c - do you want to resolve the merge conflicts, or would you like me to do that?

**Comment by gmlewis** [comment]
Thank you, @m19c !  Could you please run `gofmt` one more time and push the changes to make the tests pass?

**Comment by m19c** [comment]
Done. Intent should be fixed now.

**Comment by gmlewis** [comment]
@m19c - bonus points if you can increase the code coverage by writing a test for your new method (while we are waiting for a second LGTM).  :smile:

**Comment by m19c** [comment]
Done 👍🏽

**Review by gmlewis — APPROVED** [review]

**Review by Parker77 — APPROVED** [review]
LGTM.

**Pull request merged**
