### PR TITLE
Add DownloadContentsWithMeta to receive RepositoryContent

### PR DESCRIPTION
**Pull request by daniellanner**
Added an additional method and tests for callers to receive a
RepositoryContent when downloading a large file from a GitHub
repository. This simplifies future operations (e.g. UpdateFile)
involving the requested file.

Fixes: #1809.

### CODE REVIEW

**Review by gmlewis — APPROVED** [review]
Thank you, @daniellanner !
LGTM.

Awaiting second LGTM before merging.

**Review by wesleimp — APPROVED** [review]
💙

**Comment by daniellanner** [comment]
@wesleimp Thanks for the approval. Unfortunately, I just accidentally hit *Re-request review*. My bad. 🙈

**Comment by gmlewis** [comment]
Thank you, @wesleimp !
Merging.

**Pull request merged**
