### PR TITLE
Add requester to InstallationEvent

### PR DESCRIPTION
**Pull request by marcelosousa**
This pull request adds the `Requester` property to the `InstallationEvent` struct.

### CODE REVIEW

**Comment by gmlewis** [comment]
Relates to: #1808.

**Review by gmlewis — APPROVED** [review]
Thank you, @marcelosousa !
LGTM.
Merging.

**Comment by marcelosousa** [comment]
@gmlewis it would be great if you do a new release to incorporate this! ❤️

**Comment by gmlewis** [comment]
@marcelosousa - this is now available here: https://github.com/google/go-github/releases/tag/v52.0.0

**Pull request merged**
