### PR TITLE
Add missing fields to MarketplacePlan and MarketplacePurchase structs

### PR DESCRIPTION
**Pull request by alexal**
Hello,

As described in issue #1775, I've added missing fields to MarketplacePlan and MarketplacePurchase structs.

Thanks,
Alex

### CODE REVIEW

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @alexal , but this PR has a couple problems.
First, the issue was assigned to another person, and we try to avoid duplicating effort... however, I see in this case that it is a trivial change and no progress has been made by the other two parties, so if you can fix the other problem with this PR, we will move forward with it.

The second problem is that you need to run `go generate ./...` as described in our [CONTRIBUTING.md](https://github.com/google/go-github/blob/master/CONTRIBUTING.md) file.

Once you do this, the tests should pass and we can move forward with this PR.

Thanks.

**Comment by gmlewis** [comment]
And in the future (also listed in our CONTRIBUTING.md file - search for # 7)... please do not use force push on PRs for this repo, as it makes the reviews much more difficult for the reviewers to keep track of changes.

Obviously, for this PR, it doesn't matter, but just please keep this in mind for future contributions.

Thank you.

**Review by gmlewis — APPROVED** [review]
Thank you, @alexal !
LGTM.
Merging.

**Comment by alexal** [comment]
@gmlewis thank you. I've made all the required changes and all the tests were completed successfully.

**Pull request merged**
