### PR TITLE
Adding missing field important to find branch in fork from same owner

### PR DESCRIPTION
**Pull request by r-aramizu**
Hello there! I opened an [issue](https://github.com/google/go-github/issues/2872) to explain this suggestion.

I put the new field on your tests and keep working as before! There was a change that could solve my problem!

Fixes: #2872.

### CODE REVIEW

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @r-aramizu !
Please run `go generate ./...` in the top of the repo and then push (not force-push) the changes to this same PR, and that should fix the tests.
See CONTRIBUTING.md for more information.

**Comment by r-aramizu** [comment]
Thank you @gmlewis ! My bad for forgot this 😅 
Done!

**Comment by gmlewis** [comment]
@r-aramizu - please follow the CLA instructions from the comment above:
https://github.com/google/go-github/pull/2873#issuecomment-1679373226
in order to sign the Google CLA.  Thank you!

**Review by gmlewis — APPROVED** [review]
Thank you, @r-aramizu !
LGTM.
Merging.

**Comment by r-aramizu** [comment]
Thank you @gmlewis to review it and help me with this! 🚀

**Pull request merged**
