### PR TITLE
Fixes wrong Accept media type that was causing a 500

### PR DESCRIPTION
**Pull request by phylake**
https://developer.github.com/v3/issues/#list-issues-for-a-repository
lists
- application/vnd.github.symmetra-preview+json
- application/vnd.github.squirrel-girl-preview
- application/vnd.github.machine-man-preview

which map to

- mediaTypeLabelDescriptionSearchPreview
- mediaTypeReactionsPreview
- mediaTypeIntegrationPreview

### CODE REVIEW

**Comment by gmlewis** [comment]
Thank you, @phylake! Could you please also update the corresponding test?

This PR generates the Travis CI failure:

```
	github_test.go:115: Header.Get("Accept") returned "application/vnd.github.squirrel-girl-preview, application/vnd.github.symmetra-preview+json, application/vnd.github.machine-man-preview+json", want "application/vnd.github.squirrel-girl-preview, application/vnd.github.symmetra-preview+json, application/vnd.github.sailor-v-preview+json"
```

If you run `go test ./...` locally, you should see the problem.

**Comment by phylake** [comment]
I think Travis CI failed to update the status check. It all looks green to me. What should I do?

**Comment by gmlewis** [comment]
I restarted the build... Let's see if that fixes it.

**Comment by gmlewis** [comment]
That seems to have worked.

**Comment by gmlewis** [comment]
It looks like this was mistakenly changed in #910.
Thank you for catching and fixing this, @phylake!
LGTM.
Merging.

**Pull request merged**
