### PR TITLE
Add struct for workflow_job event

### PR DESCRIPTION
**Pull request by acuteaura**
This is a new (as of now undocumented) event that has been darkshipped by GitHub.

It provides three actions: queued, started and completed, reusing the existing WorkflowJob struct.

Official documentation is supposedly soon to follow, but advance submission of this PR has been approved by GitHub staff.

You can hold up this PR until it drops. I will update it accordingly.

### CODE REVIEW

**Comment by acuteaura** [comment]
@googlebot I signed it!

**Review by gmlewis — CHANGES_REQUESTED** [review]
Thank you, @acuteaura !
Could you please also add this new event to `ParsePayload` and also a couple more places? If you search for `WorkflowRunEvent` then you should be able to find the other locations.

**Review by gmlewis — APPROVED** [review]
Excellent, thank you, @acuteaura !
LGTM.

Awaiting second LGTM before merging.

**Review by Parker77 — APPROVED** [review]
LGTM.

**Comment by gmlewis** [comment]
Thank you, @Parker77 !
Merging.

**Pull request merged**
