### PR TITLE
Add fields to update repository API and create branch protection API to match GitHub APIs

### PR DESCRIPTION
**Pull request by verbanicm**

### CODE REVIEW

**Review by sethvargo — APPROVED** [review]

**Review by gmlewis — APPROVED** [review]
Thank you, @verbanicm and @sethvargo !
LGTM.
Merging.

**Comment by verbanicm** [comment]
Thank you @gmlewis !

**Comment by verbanicm** [comment]
@gmlewis Do you have a set release schedule or can this be cut whenever?

**Comment by gmlewis** [comment]
@verbanicm - we typically shoot for a release approximately once per month, but we are flexible and can release on demand if there is a pressing need.  We are already at 3 weeks since the last release so I can go ahead and prepare a new one.

**Comment by verbanicm** [comment]
@gmlewis No rush, but you are able, then 🎉

**Comment by gmlewis** [comment]
@verbanicm - here is the latest release: https://github.com/google/go-github/releases/tag/v50.2.0

**Comment by verbanicm** [comment]
@gmlewis Awesome, thank you!!

**Pull request merged**
