### PR TITLE
Escape branch string before inserting it in URL

### PR DESCRIPTION
**Pull request by k0ral**
When a branch name with special characters like `%` is passed to the [`RepositoryService.GetBranch()` method](https://github.com/google/go-github/blob/8cd452b85e821c32eefcc5964e91e57f9731891f/github/repos.go#L1277) as is, an error is currently returned:
```
invalid URL escape "%"
```

Passing an escaped branch name to `RepositoriesService.GetBranch()` works fine.

Here's a minimal reproducer
```golang
import (
	"context"
	"net/http"
	"testing"

	"github.com/google/go-github/v53/github"
	"github.com/stretchr/testify/require"
)

func TestGetBranch(t *testing.T) {
	t.Parallel()
	ctx := context.Background()

	githubClient := github.NewClient(&http.Client{
		Transport: http.DefaultTransport,
	})
	owner := "samstickkz"
	project := "curr"
	branchName := "Feature/authentication_90%"
	branch, response, err := githubClient.Repositories.GetBranch(ctx, owner, project, branchName, false)

	require.Nil(t, err)
	t.Logf("Response: %+v", response)
	t.Logf("Branch: %+v", branch)
}
```

This sounds like a bug to me, as I believe users of that method shouldn't be expected to escape the branch name before calling it, as this is a private implementation quirk that they shouldn't be aware of. This PR patches all branch-related methods to automatically escape the branch name in the endpoint URL. 

There's actually [a precedent for `ref` parameter](https://github.com/google/go-github/pull/2454), and I suspect that other variables are prone to the same issue. I am conservatively patching only the branch variable, as this is the only one I have tested thoroughly. Note that, contrary to `ref` use case, my tests suggest that it's okay to escape `/` characters for branch names. 

:warning: Breaking change: for users that currently _bypass_ this issue by feeding escaped strings to `RepositoryService.GetBranch()` method (and other branch-related methods), this change will be breaking.

### CODE REVIEW

**Comment by gmlewis** [comment]
Honestly, I'm quite surprised that this issue has never come up before... as this repo is how many years old? 10?!?

However, I think you are right.

I'm wondering if each of the modified endpoints needs a comment in the documentation stating something like:

```
// Note that the branch name is URL path escaped for you. See: https://pkg.go.dev/net/url#PathEscape
```

**Review by gmlewis — CHANGES_REQUESTED** [review]
Can you please add unit tests that demonstrate this new super power?

**Comment by k0ral** [comment]
@gmlewis PR updated with additional comments and unit tests.

**Review by gmlewis — APPROVED** [review]
Thank you, @k0ral !
LGTM.

Awaiting second LGTM+Approval from any other contributor to this repo before merging.

**Comment by WillAbides** [comment]
I have a bit of concern about this being a subtle breaking change that could take a long time to discover after upgrading. I'm looking at ways to mitigate that. I'll be back to review later today.

**Review by WillAbides — APPROVED** [review]
I'm still a little hesitant about the breaking change, but after a some pondering I can't come up with anything better that doesn't add unnecessary complexity.

**Comment by gmlewis** [comment]
Thank you, @WillAbides !
Merging.

**Pull request merged**
