### PR TITLE
Fix failure with 422 Validation Failed 

### PR DESCRIPTION
**Pull request by bbbmj**
**What this PR does / why we need it**:

 fix failure with 422 Validation Failed [{Resource: Field: Code: Message:}]

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by bbbmj** [comment]
I signed it!

**Comment by bbbmj** [comment]
I signed it!

**Comment by bbbmj** [comment]
I signed it!

**Comment by bbbmj** [comment]
@gmlewis @varadarajana  PTAL

**Comment by gmlewis** [comment]
This seems reasonable to me, but I would like to try it out tomorrow and also get a second LGTM before merging.
Thanks, @bbbmj!

**Comment by bbbmj** [comment]
@gmlewis PTAL

**Comment by shurcooL** [comment]
This overlaps with #791.

**Comment by gmlewis** [comment]
@bbbmj, can we close this PR now that #791 has been merged?

**Comment by bbbmj** [comment]
Of course, just close it.

**Pull request closed without merging**
