### PR TITLE
Add pagination options to list all package versions

### PR DESCRIPTION
**Pull request by lpmatos**
Here is the detail of the problem: #2251.

### CODE REVIEW

**Review by gmlewis — APPROVED** [review]
Thank you, @lpmatos !
Once you sign the CLA, we can move forward with this PR.
LGTM.

**Comment by lpmatos** [comment]
> Thank you, @lpmatos ! Once you sign the CLA, we can move forward with this PR. LGTM.

Do I have to commit using my gmail? I followed all the steps mentioned in the documentation. 

Sorry for the questions, this is my first contribution to a project like this.

## Screenshots

### CLA

Screen Shot 2022-01-12 at 01 07 32

### E-mails on GitHub

Screen Shot 2022-01-12 at 01 09 32

**Comment by gmlewis** [comment]
The CLA email needs to match the email address you associated with your GitHub commits, and it looks like you sorted it all out.  Thanks.

We are now ready for a second LGTM/Approval from any other contributor to this repo.

Maybe @Parker77 has time to review this some time today.

**Review by gmlewis — APPROVED** [review]

**Review by Parker77 — APPROVED** [review]
LGTM.

**Comment by gmlewis** [comment]
Thank you, @Parker77 !
Merging.

**Pull request merged**
